// AUTO-GENERATED by scripts/fetch-tmdb.mjs — do not edit
import type { CurationItem } from './musicbrainz';
export const FILM_ITEMS: CurationItem[] = [
  {
    "source": "film",
    "refId": "18148",
    "title": "Tokyo Story",
    "seedName": "Tokyo Story",
    "creator": "",
    "year": "1953",
    "tags": [
      "film"
    ],
    "cover": "/images/film/film-18148.webp",
    "url": "/film/"
  },
  {
    "source": "film",
    "refId": "1398",
    "title": "Stalker",
    "seedName": "Stalker",
    "creator": "",
    "year": "1979",
    "tags": [
      "film"
    ],
    "cover": "/images/film/film-1398.webp",
    "url": "/film/"
  },
  {
    "source": "film",
    "refId": "23160",
    "title": "Werckmeister Harmonies",
    "seedName": "Werckmeister Harmonies",
    "creator": "",
    "year": "2001",
    "tags": [
      "film"
    ],
    "cover": "/images/film/film-23160.webp",
    "url": "/film/"
  },
  {
    "source": "film",
    "refId": "463258",
    "title": "Colossal Youth",
    "seedName": "Colossal Youth",
    "creator": "",
    "year": "2018",
    "tags": [
      "film"
    ],
    "cover": "/images/film/film-463258.webp",
    "url": "/film/"
  },
  {
    "source": "film",
    "refId": "114982",
    "title": "Goodbye to Language",
    "seedName": "Goodbye to Language",
    "creator": "",
    "year": "2014",
    "tags": [
      "film"
    ],
    "cover": "/images/film/film-114982.webp",
    "url": "/film/"
  },
  {
    "source": "film",
    "refId": "8967",
    "title": "The Tree of Life",
    "seedName": "The Tree of Life",
    "creator": "",
    "year": "2011",
    "tags": [
      "film"
    ],
    "cover": "/images/film/film-8967.webp",
    "url": "/film/"
  },
  {
    "source": "film",
    "refId": "74879",
    "title": "Once Upon a Time in Anatolia",
    "seedName": "Once Upon a Time in Anatolia",
    "creator": "",
    "year": "2011",
    "tags": [
      "film"
    ],
    "cover": "/images/film/film-74879.webp",
    "url": "/film/"
  },
  {
    "source": "film",
    "refId": "31414",
    "title": "Satantango",
    "seedName": "Sátántangó",
    "creator": "",
    "year": "1994",
    "tags": [
      "film"
    ],
    "cover": "/images/film/film-31414.webp",
    "url": "/film/"
  },
  {
    "source": "film",
    "refId": "829",
    "title": "Chinatown",
    "seedName": "Chinatown",
    "creator": "",
    "year": "1974",
    "tags": [
      "film"
    ],
    "cover": "/images/film/film-829.webp",
    "url": "/film/"
  },
  {
    "source": "film",
    "refId": "807",
    "title": "Se7en",
    "seedName": "Se7en",
    "creator": "",
    "year": "1995",
    "tags": [
      "film"
    ],
    "cover": "/images/film/film-807.webp",
    "url": "/film/"
  },
  {
    "source": "film",
    "refId": "1018",
    "title": "Mulholland Drive",
    "seedName": "Mulholland Drive",
    "creator": "",
    "year": "2001",
    "tags": [
      "film"
    ],
    "cover": "/images/film/film-1018.webp",
    "url": "/film/"
  }
];
