// AUTO-GENERATED by scripts/fetch-rawg.mjs — do not edit
import type { CurationItem } from './musicbrainz';
export const GAME_ITEMS: CurationItem[] = [
  {
    "source": "game",
    "refId": "2551",
    "title": "Dark Souls III",
    "seedName": "DARK SOULS III",
    "creator": "Action, RPG",
    "year": "2016",
    "tags": [
      "action",
      "role-playing-games-rpg",
      "pc",
      "xbox-one",
      "playstation4"
    ],
    "cover": "/images/games/game-2551.webp",
    "url": "/games/soulslike-lineage",
    "synopsis": "Dark Souls III is the fourth installment in the Dark Souls series, now introducing the players to the world of Lothric, a kingdom which has suffered the fate similar to its counterparts from the previous games, descending from…",
    "moods": []
  },
  {
    "source": "game",
    "refId": "326243",
    "title": "Elden Ring",
    "seedName": "Elden Ring",
    "creator": "Action, RPG",
    "year": "2022",
    "tags": [
      "action",
      "role-playing-games-rpg",
      "pc",
      "playstation5",
      "xbox-one",
      "playstation4",
      "xbox-series-x"
    ],
    "cover": "/images/games/game-326243.webp",
    "url": "/games/soulslike-lineage",
    "synopsis": "The Golden Order has been broken. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.",
    "moods": []
  },
  {
    "source": "game",
    "refId": "3387",
    "title": "Bloodborne",
    "seedName": "Bloodborne",
    "creator": "Action, RPG",
    "year": "2015",
    "tags": [
      "action",
      "role-playing-games-rpg",
      "playstation4"
    ],
    "cover": "/images/games/game-3387.webp",
    "url": "/games/soulslike-lineage",
    "synopsis": "Bloodborne is an action-RPG and another member of souls-like title series. The game has no predecessors or successors, making it the only entry with one add-on: “The Old Hunters.” The Bloodborne universe, however, also…",
    "moods": []
  },
  {
    "source": "game",
    "refId": "4108",
    "title": "Demon's Souls",
    "seedName": "Demon Souls",
    "creator": "Action, RPG",
    "year": "2009",
    "tags": [
      "action",
      "role-playing-games-rpg",
      "playstation3"
    ],
    "cover": "/images/games/game-4108.webp",
    "url": "/games/soulslike-lineage",
    "moods": []
  },
  {
    "source": "game",
    "refId": "433707",
    "title": "Sekiro",
    "seedName": "Sekiro",
    "creator": "",
    "year": "2020",
    "tags": [
      "pc"
    ],
    "cover": "/images/games/game-433707.webp",
    "url": "/games/soulslike-lineage",
    "synopsis": "Sekiro is a game developed by romanstarner. It was originally released in 2020.",
    "moods": []
  },
  {
    "source": "game",
    "refId": "605674",
    "title": "Lies Of P",
    "seedName": "Lies of P",
    "creator": "Action, RPG",
    "year": "2023",
    "tags": [
      "action",
      "role-playing-games-rpg",
      "pc",
      "playstation5",
      "xbox-one",
      "playstation4",
      "xbox-series-x",
      "macos"
    ],
    "cover": "/images/games/game-605674.webp",
    "url": "/games/soulslike-lineage",
    "synopsis": "You wake up at an abandoned train station in Krat, a city overwhelmed by madness and bloodlust. In front of you lies a single note that reads: \"Find Mr.",
    "moods": []
  },
  {
    "source": "game",
    "refId": "401",
    "title": "Nioh",
    "seedName": "Nioh",
    "creator": "Action, RPG",
    "year": "2017",
    "tags": [
      "action",
      "role-playing-games-rpg",
      "pc",
      "playstation4"
    ],
    "cover": "/images/games/game-401.webp",
    "url": "/games/soulslike-lineage",
    "synopsis": "Dead or alive A game of insane complexity in the best traditions of the Dark Souls series, the games of which set the standard of quality in the genre.",
    "moods": []
  },
  {
    "source": "game",
    "refId": "9767",
    "title": "Hollow Knight",
    "seedName": "Hollow Knight",
    "creator": "Platformer, Indie, Action",
    "year": "2017",
    "tags": [
      "platformer",
      "indie",
      "action",
      "pc",
      "xbox-one",
      "playstation4",
      "nintendo-switch",
      "macos"
    ],
    "cover": "/images/games/game-9767.webp",
    "url": "/games/soulslike-lineage",
    "synopsis": "Hollow Knight is a Metroidvania-type game developed by an indie studio named Team Cherry. Most of the game's story is told through the in-world items, tablets, and thoughts of other characters.",
    "moods": []
  },
  {
    "source": "game",
    "refId": "25137",
    "title": "Castlevania",
    "seedName": "Castlevania",
    "creator": "Platformer, Arcade, Action",
    "year": "1986",
    "tags": [
      "platformer",
      "arcade",
      "action",
      "pc",
      "playstation4",
      "nintendo-switch",
      "nintendo-3ds",
      "wii-u"
    ],
    "cover": "/images/games/game-25137.webp",
    "url": "/games/metroidvania-map",
    "synopsis": "Beware of Dracula and his ghoulish minions as you enter his lair… Castlevania marked the beginning of Konami’s acclaimed series, one that is still going strong today!",
    "moods": []
  },
  {
    "source": "game",
    "refId": "622495",
    "title": "Metroid Dread",
    "seedName": "Metroid Dread",
    "creator": "Platformer, Action, RPG",
    "year": "2021",
    "tags": [
      "platformer",
      "action",
      "role-playing-games-rpg",
      "nintendo-switch"
    ],
    "cover": "/images/games/game-622495.webp",
    "url": "/games/metroidvania-map",
    "moods": []
  },
  {
    "source": "game",
    "refId": "11726",
    "title": "Dead Cells",
    "seedName": "Dead Cells",
    "creator": "Platformer, Indie, Action, RPG",
    "year": "2018",
    "tags": [
      "platformer",
      "indie",
      "action",
      "role-playing-games-rpg",
      "pc",
      "xbox-one",
      "playstation4",
      "nintendo-switch"
    ],
    "cover": "/images/games/game-11726.webp",
    "url": "/games/metroidvania-map",
    "synopsis": "Dead Cells is a roguelike adventure title developed by Motion Twin. Not much is present in the game, as only bits of any information are given out to the players.",
    "moods": []
  },
  {
    "source": "game",
    "refId": "22121",
    "title": "Celeste",
    "seedName": "Celeste",
    "creator": "Platformer, Indie",
    "year": "2018",
    "tags": [
      "platformer",
      "indie",
      "pc",
      "xbox-one",
      "playstation4",
      "nintendo-switch",
      "macos",
      "linux"
    ],
    "cover": "/images/games/game-22121.webp",
    "url": "/games/metroidvania-map",
    "synopsis": "Celeste is a platformer about climbing a mountain, from the creators of TowerFall. Explore a sprawling mountain with over 500 levels bursting with secrets, across 8 unique areas.",
    "moods": []
  },
  {
    "source": "game",
    "refId": "2536",
    "title": "Axiom Verge",
    "seedName": "Axiom Verge",
    "creator": "Indie, Platformer, Adventure, Action",
    "year": "2015",
    "tags": [
      "indie",
      "platformer",
      "adventure",
      "action",
      "pc",
      "xbox-one",
      "playstation4",
      "nintendo-switch"
    ],
    "cover": "/images/games/game-2536.webp",
    "url": "/games/metroidvania-map",
    "synopsis": "This is the action-adventure you’ve been waiting decades for. After a lab accident, a scientist awakens in a mysterious, alien world.",
    "moods": []
  },
  {
    "source": "game",
    "refId": "286485",
    "title": "SteamWorld Quest: Hand of Gilgamech",
    "seedName": "Steamworld",
    "creator": "Card, Adventure, Action, RPG",
    "year": "2019",
    "tags": [
      "card",
      "adventure",
      "action",
      "role-playing-games-rpg",
      "pc",
      "nintendo-switch",
      "ios",
      "macos"
    ],
    "cover": "/images/games/game-286485.webp",
    "url": "/games/metroidvania-map",
    "synopsis": "SteamWorld Quest is the roleplaying card game you’ve been waiting for! Lead a party of aspiring heroes through a beautifully hand-drawn world and intense battles using only your wits and a handful of cards.",
    "moods": []
  },
  {
    "source": "game",
    "refId": "654",
    "title": "Stardew Valley",
    "seedName": "Stardew Valley",
    "creator": "Indie, RPG, Simulation",
    "year": "2016",
    "tags": [
      "indie",
      "role-playing-games-rpg",
      "simulation",
      "pc",
      "xbox-one",
      "playstation4",
      "nintendo-switch",
      "ios"
    ],
    "cover": "/images/games/game-654.webp",
    "url": "/games/cozy-games",
    "synopsis": "The hero (in the beginning you can choose gender, name and appearance) - an office worker who inherited an abandoned farm. The landscape of the farm can also be selected.",
    "moods": []
  },
  {
    "source": "game",
    "refId": "54346",
    "title": "Animal Crossing",
    "seedName": "Animal Crossing",
    "creator": "RPG, Simulation",
    "year": "2001",
    "tags": [
      "role-playing-games-rpg",
      "simulation",
      "gamecube",
      "nintendo-64"
    ],
    "cover": "/images/games/game-54346.webp",
    "url": "/games/cozy-games",
    "moods": []
  },
  {
    "source": "game",
    "refId": "326236",
    "title": "Spiritfarer",
    "seedName": "Spiritfarer",
    "creator": "Indie, Adventure, Simulation",
    "year": "2020",
    "tags": [
      "indie",
      "adventure",
      "simulation",
      "pc",
      "xbox-one",
      "playstation4",
      "nintendo-switch",
      "macos"
    ],
    "cover": "/images/games/game-326236.webp",
    "url": "/games/cozy-games",
    "synopsis": "What will you leave behind? Spiritfarer is a cozy management game about dying.",
    "moods": []
  },
  {
    "source": "game",
    "refId": "364942",
    "title": "Unpacking",
    "seedName": "Unpacking",
    "creator": "Casual",
    "year": "2021",
    "tags": [
      "casual",
      "pc",
      "playstation5",
      "xbox-one",
      "playstation4",
      "xbox-series-x",
      "nintendo-switch",
      "macos"
    ],
    "cover": "/images/games/game-364942.webp",
    "url": "/games/cozy-games",
    "moods": []
  },
  {
    "source": "game",
    "refId": "304247",
    "title": "A Short Hike",
    "seedName": "A Short Hike",
    "creator": "Indie, Adventure",
    "year": "2019",
    "tags": [
      "indie",
      "adventure",
      "pc",
      "playstation4",
      "nintendo-switch",
      "macos",
      "linux"
    ],
    "cover": "/images/games/game-304247.webp",
    "url": "/games/cozy-games",
    "synopsis": "Hike, climb, and soar through the peaceful mountainside landscapes of Hawk Peak Provincial Park. Follow the marked trails or explore the backcountry as you make your way to the summit.",
    "moods": []
  },
  {
    "source": "game",
    "refId": "57375",
    "title": "Harvest Moon",
    "seedName": "Harvest Moon",
    "creator": "RPG, Simulation",
    "year": "1996",
    "tags": [
      "role-playing-games-rpg",
      "simulation",
      "nintendo-3ds",
      "wii-u",
      "wii",
      "snes"
    ],
    "cover": "/images/games/game-57375.webp",
    "url": "/games/cozy-games",
    "synopsis": "Harvest Moon (牧場物語, Bokujō Monogatari, lit. \"Farm \") is a farm simulation role-playing game developed by Amccus for the Super Nintendo Entertainment System.",
    "moods": []
  },
  {
    "source": "game",
    "refId": "117349",
    "title": "What Remains",
    "seedName": "What Remains",
    "creator": "Adventure",
    "year": "2014",
    "tags": [
      "adventure",
      "pc"
    ],
    "cover": "/images/games/game-117349.webp",
    "url": "/games/narrative-walking",
    "synopsis": "Waking with a pounding headache, you find yourself in a mansion on the eve of 1930 - but you are not alone.What Remains is a horror game originally created for the Asylum Jam 2014 ( asylumjam) and has since been worked into a…",
    "moods": []
  }
];
