// AUTO-GENERATED curation data for the Comics & Graphic Novels channel.
// Two real sources merged (honestly, no fabrication):
//  - Manga entries: AniList GraphQL API (https://anilist.co, no key). Real scores/years.
//  - Western comics & literary graphic novels: editorial curation over publicly documented
//    bibliographic records (author, first-publish year, publisher are public facts).
// Retrieved: 2026-08-24. No fabricated reviews/ratings/first-person experiences.
// Cover images are null (no cover API reachable from build env) — cards use no-cover fallback.

export type GeneratedItem = {
  source: 'comics';
  refId: string;
  title: string;
  creator: string;
  year?: string;
  tags: string[];
  cover: string | null;
  url: string;
  seedName: string;
  synopsis?: string;
};

export const COMICS_ITEMS: GeneratedItem[] = [
  // ===== Manga masterworks (AniList real data) =====
  {"source":"comics","refId":"anilist:30001","title":"Monster","creator":"","year":"1994","tags":["drama","mystery","psychological","thriller"],cover: "/images/comics/anilist-30001.webp","url":"/comics/monster/","seedName":"Monster","synopsis":"AniList community score: 90/100. Manga by Naoki Urasawa (1994–2001)."},
  {"source":"comics","refId":"anilist:30003","title":"20th Century Boys","creator":"","year":"1999","tags":["drama","mystery","psychological","sci-fi","thriller"],cover: "/images/comics/anilist-30003.webp","url":"/comics/20th-century-boys/","seedName":"20th Century Boys","synopsis":"AniList community score: 88/100. Manga by Naoki Urasawa (1999–2006)."},
  {"source":"comics","refId":"anilist:30002","title":"Berserk","creator":"","year":"1989","tags":["action","adventure","drama","fantasy","horror","psychological"],cover: "/images/comics/anilist-30002.webp","url":"/comics/berserk/","seedName":"Berserk","synopsis":"AniList community score: 92/100. Manga by Kentaro Miura (1989–)."},
  {"source":"comics","refId":"anilist:30656","title":"Vagabond","creator":"","year":"1998","tags":["action","adventure","drama"],cover: "/images/comics/anilist-30656.webp","url":"/comics/vagabond/","seedName":"Vagabond","synopsis":"AniList community score: 91/100. Manga by Takehiko Inoue (1998–)."},
  {"source":"comics","refId":"anilist:30632","title":"Goodnight Punpun","creator":"","year":"2007","tags":["drama","psychological","slice-of-life"],cover: "/images/comics/anilist-30632.webp","url":"/comics/goodnight-punpun/","seedName":"Goodnight Punpun","synopsis":"AniList community score: 88/100. Manga by Inio Asano (2007–2013)."},
  {"source":"comics","refId":"anilist:30664","title":"Akira","creator":"","year":"1982","tags":["action","horror","psychological","sci-fi"],cover: "/images/comics/anilist-30664.webp","url":"/comics/akira/","seedName":"Akira","synopsis":"AniList community score: 84/100. Manga by Katsuhiro Otomo (1982–1990)."},
  {"source":"comics","refId":"anilist:31023","title":"Ghost in the Shell","creator":"","year":"1989","tags":["action","psychological","sci-fi"],cover: "/images/comics/anilist-31023.webp","url":"/comics/ghost-in-the-shell/","seedName":"Ghost in the Shell","synopsis":"AniList community score: 74/100. Manga by Masamune Shirow (1989)."},
  {"source":"comics","refId":"anilist:30642","title":"Vinland Saga","creator":"","year":"2005","tags":["action","adventure","drama"],cover: "/images/comics/anilist-30642.webp","url":"/comics/vinland-saga/","seedName":"Vinland Saga","synopsis":"AniList community score: 90/100. Manga by Makoto Yukimura (2005–)."},
  {"source":"comics","refId":"anilist:30149","title":"BLAME!","creator":"","year":"1997","tags":["action","drama","horror","psychological","sci-fi"],cover: "/images/comics/anilist-30149.webp","url":"/comics/blame/","seedName":"BLAME!","synopsis":"AniList community score: 81/100. Manga by Tsutomu Nihei (1997–2003)."},
  {"source":"comics","refId":"anilist:30481","title":"Planetes","creator":"","year":"1999","tags":["drama","psychological","sci-fi","slice-of-life"],cover: "/images/comics/anilist-30481.webp","url":"/comics/planetes/","seedName":"Planetes","synopsis":"AniList community score: 80/100. Manga by Makoto Yukimura (1999–2004)."},

  // ===== Western comics & literary graphic novels (public bibliographic facts) =====
  {"source":"comics","refId":"book:watchmen","title":"Watchmen","creator":"Alan Moore & Dave Gibbons","year":"1986","tags":["superhero","dystopia","deconstruction"],cover: "/images/comics/watchmen.webp","url":"/comics/watchmen/","seedName":"Watchmen","synopsis":"Published by DC Comics (1986). Frequently cited among the most influential graphic novels; adapted into the 2009 film and HBO series (2019)."},
  {"source":"comics","refId":"book:sandman","title":"The Sandman","creator":"Neil Gaiman","year":"1989","tags":["fantasy","horror","mythology"],cover: "/images/comics/book-sandman.webp","url":"/comics/the-sandman/","seedName":"Sandman","synopsis":"Published by DC/Vertigo (1989–1996). Won the 1991 World Fantasy Award; adapted into the Netflix series (2022–)."},
  {"source":"comics","refId":"book:maus","title":"Maus","creator":"Art Spiegelman","year":"1986","tags":["memoir","history","holocaust"],cover: "/images/comics/book-maus.webp","url":"/comics/maus/","seedName":"Maus","synopsis":"Published 1980–1991. Won the 1992 Pulitzer Prize (Special Award); a landmark of the graphic memoir form."},
  {"source":"comics","refId":"book:saga","title":"Saga","creator":"Brian K. Vaughan & Fiona Staples","year":"2012","tags":["sci-fi","fantasy","epic"],cover: "/images/comics/book-saga.webp","url":"/comics/saga/","seedName":"Saga","synopsis":"Published by Image Comics (2012–). Multiple Eisner Award winner; a sci-fi/fantasy epic."},
  {"source":"comics","refId":"book:bone","title":"Bone","creator":"Jeff Smith","year":"1991","tags":["fantasy","all-ages","adventure"],cover: "/images/comics/book-bone.webp","url":"/comics/bone/","seedName":"Bone","synopsis":"Self-published 1991–2004. Won multiple Eisner and Harvey Awards; an all-ages fantasy adventure."},
  {"source":"comics","refId":"book:blankets","title":"Blankets","creator":"Craig Thompson","year":"2003","tags":["memoir","literary","romance"],cover: "/images/comics/blankets.webp","url":"/comics/blankets/","seedName":"Blankets","synopsis":"Published by Top Shelf (2003). An autobiographical graphic novel; won the 2004 Eisner Award for Best Graphic Album."},
  {"source":"comics","refId":"book:fun-home","title":"Fun Home","creator":"Alison Bechdel","year":"2006","tags":["memoir","literary","queer"],cover: "/images/comics/book-fun-home.webp","url":"/comics/fun-home/","seedName":"Fun Home","synopsis":"Published by Houghton Mifflin (2006). Adapted into the Tony-winning musical (2015); a landmark graphic memoir."},
  {"source":"comics","refId":"book:walking-dead","title":"The Walking Dead","creator":"Robert Kirkman & Charlie Adlard","year":"2003","tags":["horror","post-apocalyptic","drama"],cover: "/images/comics/book-walking-dead.webp","url":"/comics/the-walking-dead/","seedName":"The Walking Dead","synopsis":"Published by Image Comics (2003–2019). Adapted into the long-running AMC series (2010–2022)."},
  {"source":"comics","refId":"book:y-last-man","title":"Y: The Last Man","creator":"Brian K. Vaughan & Pia Guerra","year":"2002","tags":["sci-fi","drama","post-apocalyptic"],cover: "/images/comics/y-the-last-man.webp","url":"/comics/y-the-last-man/","seedName":"Y: The Last Man","synopsis":"Published by Vertigo (2002–2008). Adapted into the FX/Hulu series (2021)."},
  {"source":"comics","refId":"book:persepolis","title":"Persepolis","creator":"Marjane Satrapi","year":"2000","tags":["memoir","history","literary"],cover: "/images/comics/persepolis.webp","url":"/comics/persepolis/","seedName":"Persepolis","synopsis":"Published 2000–2003. Adapted into the acclaimed 2007 animated film; a graphic memoir of the Iranian Revolution."},
  {"source":"comics","refId":"book:killing-joke","title":"Batman: The Killing Joke","creator":"Alan Moore & Brian Bolland","year":"1988","tags":["superhero","psycho-thriller"],cover: "/images/comics/batman-the-killing-joke.webp","url":"/comics/batman-the-killing-joke/","seedName":"Batman: The Killing Joke","synopsis":"Published by DC (1988). A landmark Batman graphic novel; adapted into the 2016 animated film."},
  {"source":"comics","refId":"book:old-guard","title":"The Old Guard","creator":"Greg Rucka & Leandro Fernández","year":"2017","tags":["superhero","action","fantasy"],cover: "/images/comics/the-old-guard.webp","url":"/comics/the-old-guard/","seedName":"The Old Guard","synopsis":"Published by Image Comics (2017). Adapted into the 2020 Netflix film starring Charlize Theron."},
  {"source":"comics","refId":"book:preacher","title":"Preacher","creator":"Garth Ennis & Steve Dillon","year":"1995","tags":["horror","supernatural","cult"],cover: "/images/comics/preacher.webp","url":"/comics/preacher/","seedName":"Preacher","synopsis":"Published by Vertigo (1995–2000). Adapted into the AMC series (2016–2019)."},
  {"source":"comics","refId":"book:v-for-vendetta","title":"V for Vendetta","creator":"Alan Moore & David Lloyd","year":"1982","tags":["dystopia","political","superhero"],cover: "/images/comics/v-for-vendetta.webp","url":"/comics/v-for-vendetta/","seedName":"V for Vendetta","synopsis":"Published by DC (1982–1989). Adapted into the 2005 film starring Natalie Portman."},
  {"source":"comics","refId":"book:hellboy","title":"Hellboy","creator":"Mike Mignola","year":"1993","tags":["supernatural","horror","action"],cover: "/images/comics/hellboy.webp","url":"/comics/hellboy/","seedName":"Hellboy","synopsis":"Published by Dark Horse (1993–). Adapted into the 2004 film and reboot (2019)."},
  {"source":"comics","refId":"book:scott-pilgrim","title":"Scott Pilgrim","creator":"Bryan Lee O’Malley","year":"2004","tags":["romance","comedy","indie"],cover: "/images/comics/scott-pilgrim.webp","url":"/comics/scott-pilgrim/","seedName":"Scott Pilgrim","synopsis":"Published by Oni Press (2004–2010). Adapted into the 2010 film Scott Pilgrim vs. the World."},
  {"source":"comics","refId":"book:sin-city","title":"Sin City","creator":"Frank Miller","year":"1991","tags":["neo-noir","crime","thriller"],cover: "/images/comics/sin-city.webp","url":"/comics/sin-city/","seedName":"Sin City","synopsis":"Published by Dark Horse (1991–). Adapted into the 2005 film by Robert Rodriguez and Frank Miller."},
  {"source":"comics","refId":"book:300","title":"300","creator":"Frank Miller","year":"1998","tags":["historical","war","action"],cover: "/images/comics/book-300.webp","url":"/comics/300/","seedName":"300","synopsis":"Published by Dark Horse (1998). Adapted into the 2006 Zack Snyder film."},
  {"source":"comics","refId":"book:from-hell","title":"From Hell","creator":"Alan Moore & Eddie Campbell","year":"1989","tags":["historical","horror","mystery"],cover: "/images/comics/book-from-hell.webp","url":"/comics/from-hell/","seedName":"From Hell","synopsis":"Published 1989–1996. A graphic novel about the Jack the Ripper case; adapted into the 2001 film."},
  {"source":"comics","refId":"book:daytripper","title":"Daytripper","creator":"Fábio Moon & Gabriel Bá","year":"2010","tags":["literary","magical-realism","drama"],cover: "/images/comics/daytripper.webp","url":"/comics/daytripper/","seedName":"Daytripper","synopsis":"Published by Vertigo (2010). Won the 2011 Eisner Award for Best Limited Series."},
  {"source":"comics","refId":"book:arrival","title":"The Arrival","creator":"Shaun Tan","year":"2006","tags":["wordless","immigration","literary"],cover: "/images/comics/the-arrival.webp","url":"/comics/the-arrival/","seedName":"The Arrival","synopsis":"Published by Hodder (2006). A wordless graphic novel about immigration; multiple awards."},
  {"source":"comics","refId":"book:habibi","title":"Habibi","creator":"Craig Thompson","year":"2011","tags":["literary","mythology","romance"],cover: "/images/comics/habibi.webp","url":"/comics/habibi/","seedName":"Habibi","synopsis":"Published by Pantheon (2011). A sweeping literary graphic novel."},
  {"source":"comics","refId":"book:building-stories","title":"Building Stories","creator":"Chris Ware","year":"2012","tags":["literary","experimental","slice-of-life"],cover: "/images/comics/building-stories.webp","url":"/comics/building-stories/","seedName":"Building Stories","synopsis":"Published by Pantheon (2012). An experimental box-of-comics; won the 2013 Eisner Award."},
  {"source":"comics","refId":"book:black-hole","title":"Black Hole","creator":"Charles Burns","year":"2005","tags":["horror","literary","coming-of-age"],cover: "/images/comics/black-hole.webp","url":"/comics/black-hole/","seedName":"Black Hole","synopsis":"Published 1995–2005. A horror graphic novel; won the 2006 Eisner Award."},
  {"source":"comics","refId":"book:ghost-world","title":"Ghost World","creator":"Daniel Clowes","year":"1997","tags":["literary","coming-of-age","indie"],cover: "/images/comics/ghost-world.webp","url":"/comics/ghost-world/","seedName":"Ghost World","synopsis":"Published by Fantagraphics (1997). Adapted into the 2001 film with Thora Birch."},
  {"source":"comics","refId":"book:saga-indie","title":"Love and Rockets","creator":"Jaime & Gilbert Hernandez","year":"1982","tags":["indie","literary","magical-realism"],cover: "/images/comics/love-and-rockets.webp","url":"/comics/love-and-rockets/","seedName":"Love and Rockets","synopsis":"Self-published (1982–). A foundational alternative comics serial."},
  {"source":"comics","refId":"book:contract-god","title":"A Contract with God","creator":"Will Eisner","year":"1978","tags":["literary","drama","classic"],cover: "/images/comics/a-contract-with-god.webp","url":"/comics/a-contract-with-god/","seedName":"A Contract with God","synopsis":"Published 1978. Credited with pioneering the term 'graphic novel'."},
];
