// AUTO-GENERATED by scripts/fetch-tmdb.mjs — do not edit
import type { CurationItem } from './musicbrainz';
export const TV_ITEMS: CurationItem[] = [
  {
    "source": "tv",
    "refId": "1398",
    "title": "The Sopranos",
    "seedName": "The Sopranos",
    "creator": "",
    "year": "1999",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-1398.webp",
    "url": "/tv/antihero-golden/",
    "synopsis": "The story of New Jersey-based Italian-American mobster Tony Soprano and the difficulties he faces as he tries to balance the conflicting requirements of his home life and the criminal organization he heads."
  },
  {
    "source": "tv",
    "refId": "1396",
    "title": "Breaking Bad",
    "seedName": "Breaking Bad",
    "creator": "",
    "year": "2008",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-1396.webp",
    "url": "/tv/antihero-golden/",
    "synopsis": "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live."
  },
  {
    "source": "tv",
    "refId": "1104",
    "title": "Mad Men",
    "seedName": "Mad Men",
    "creator": "",
    "year": "2007",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-1104.webp",
    "url": "/tv/antihero-golden/",
    "synopsis": "Set in 1960-1970 New York, this sexy, stylized and provocative drama follows the lives of the ruthlessly competitive men and women of Madison Avenue advertising."
  },
  {
    "source": "tv",
    "refId": "1438",
    "title": "The Wire",
    "seedName": "The Wire",
    "creator": "",
    "year": "2002",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-1438.webp",
    "url": "/tv/antihero-golden/",
    "synopsis": "Told from the points of view of both the Baltimore homicide and narcotics detectives and their targets, the series captures a universe in which the national war on drugs has become a permanent, self-sustaining bureaucracy, and…"
  },
  {
    "source": "tv",
    "refId": "1425",
    "title": "House of Cards",
    "seedName": "House of Cards",
    "creator": "",
    "year": "2013",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-1425.webp",
    "url": "/tv/antihero-golden/",
    "synopsis": "Betrayed by the White House, Congressman Frank Underwood embarks on a ruthless rise to power. Blackmail, seduction and ambition are his weapons."
  },
  {
    "source": "tv",
    "refId": "1405",
    "title": "Dexter",
    "seedName": "Dexter",
    "creator": "",
    "year": "2006",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-1405.webp",
    "url": "/tv/antihero-golden/",
    "synopsis": "Dexter Morgan, a blood spatter pattern analyst for the Miami Metro Police also leads a secret life as a serial killer, hunting down criminals who have slipped through the cracks of justice."
  },
  {
    "source": "tv",
    "refId": "69740",
    "title": "Ozark",
    "seedName": "Ozark",
    "creator": "",
    "year": "2017",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-69740.webp",
    "url": "/tv/antihero-golden/",
    "synopsis": "A financial adviser drags his family from Chicago to the Missouri Ozarks, where he must launder $500 million in five years to appease a drug boss."
  },
  {
    "source": "tv",
    "refId": "76331",
    "title": "Succession",
    "seedName": "Succession",
    "creator": "",
    "year": "2018",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-76331.webp",
    "url": "/tv/antihero-golden/",
    "synopsis": "Follow the lives of the Roy family as they contemplate their future once their aging father begins to step back from the media and entertainment conglomerate they control."
  },
  {
    "source": "tv",
    "refId": "87108",
    "title": "Chernobyl",
    "seedName": "Chernobyl",
    "creator": "",
    "year": "2019",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-87108.webp",
    "url": "/tv/limited-series-tight/",
    "synopsis": "The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster."
  },
  {
    "source": "tv",
    "refId": "87739",
    "title": "The Queen's Gambit",
    "seedName": "The Queen Gambit",
    "creator": "",
    "year": "2020",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-87739.webp",
    "url": "/tv/limited-series-tight/"
  },
  {
    "source": "tv",
    "refId": "61585",
    "title": "Olive Kitteridge",
    "seedName": "Olive Kitteridge",
    "creator": "",
    "year": "2014",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-61585.webp",
    "url": "/tv/limited-series-tight/",
    "synopsis": "A look at a seemingly placid New England town that is actually wrought with illicit affairs, crime and tragedy, all told through the lens of Olive, whose wicked wit and harsh demeanor mask a warm but troubled heart and staunch…"
  },
  {
    "source": "tv",
    "refId": "70453",
    "title": "Sharp Objects",
    "seedName": "Sharp Objects",
    "creator": "",
    "year": "2018",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-70453.webp",
    "url": "/tv/limited-series-tight/",
    "synopsis": "Reporter Camille Preaker confronts the psychological demons from her past when she returns to her hometown to investigate the murders of two young girls."
  },
  {
    "source": "tv",
    "refId": "115004",
    "title": "Mare of Easttown",
    "seedName": "Mare of Easttown",
    "creator": "",
    "year": "2021",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-115004.webp",
    "url": "/tv/limited-series-tight/",
    "synopsis": "A detective in a small Pennsylvania town investigates a local murder while trying to keep her life from falling apart."
  },
  {
    "source": "tv",
    "refId": "80039",
    "title": "The Underground Railroad",
    "seedName": "The Underground Railroad",
    "creator": "",
    "year": "2021",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-80039.webp",
    "url": "/tv/limited-series-tight/",
    "synopsis": "Follow young Cora’s journey as she makes a desperate bid for freedom in the antebellum South. After escaping her Georgia plantation for the rumored Underground Railroad, Cora discovers no mere metaphor, but an actual railroad…"
  },
  {
    "source": "tv",
    "refId": "89905",
    "title": "Normal People",
    "seedName": "Normal People",
    "creator": "",
    "year": "2020",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-89905.webp",
    "url": "/tv/limited-series-tight/",
    "synopsis": "Marianne and Connell weave in and out of each other's lives in this exploration of sex, power and the desire to love and be loved."
  },
  {
    "source": "tv",
    "refId": "67070",
    "title": "Fleabag",
    "seedName": "Fleabag",
    "creator": "",
    "year": "2016",
    "tags": [
      "tv"
    ],
    "cover": null,
    "url": "/tv/british-dry/",
    "synopsis": "A portrait into the mind of a dry-witted, sexual, angry, porn-watching, grief-riddled woman, trying to make sense of the world. As she hurls herself headlong at modern living, Fleabag is thrown roughly up against the walls of…"
  },
  {
    "source": "tv",
    "refId": "815",
    "title": "Peep Show",
    "seedName": "Peep Show",
    "creator": "",
    "year": "2003",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-815.webp",
    "url": "/tv/british-dry/",
    "synopsis": "Two dysfunctional flatmates reveal all their inner thoughts - whether dark, stupid or embarrassing. Or, occasionally, all three..."
  },
  {
    "source": "tv",
    "refId": "2490",
    "title": "The IT Crowd",
    "seedName": "IT Crowd",
    "creator": "",
    "year": "2006",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-2490.webp",
    "url": "/tv/british-dry/",
    "synopsis": "The comedic misadventures of Roy, Moss, and their grifting supervisor Jen, a 'motley crew' of IT support workers at a large corporation headed by a hotheaded yuppie."
  },
  {
    "source": "tv",
    "refId": "903",
    "title": "Black Books",
    "seedName": "Black Books",
    "creator": "",
    "year": "2000",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-903.webp",
    "url": "/tv/british-dry/",
    "synopsis": "Black Books centres around the foul tempered and wildly eccentric bookshop owner Bernard Black. Bernard’s devotion to the twin pleasures of drunkenness and wilful antagonism deepens and enriches both his life and that of…"
  },
  {
    "source": "tv",
    "refId": "61828",
    "title": "Detectorists",
    "seedName": "Detectorists",
    "creator": "",
    "year": "2014",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-61828.webp",
    "url": "/tv/british-dry/",
    "synopsis": "The lives of two eccentric metal detectorists, who spend their days plodding along ploughed tracks and open fields, hoping to disturb the tedium by unearthing the fortune of a lifetime."
  },
  {
    "source": "tv",
    "refId": "4507",
    "title": "The Thick of It",
    "seedName": "The Thick of It",
    "creator": "",
    "year": "2005",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-4507.webp",
    "url": "/tv/british-dry/",
    "synopsis": "Set in the corridors of power and spin, the Minister for Social Affairs is continually harassed by Number 10's policy enforcer and dependent on his not-so-reliable team of civil servants."
  },
  {
    "source": "tv",
    "refId": "54344",
    "title": "The Leftovers",
    "seedName": "The Leftovers",
    "creator": "",
    "year": "2014",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-54344.webp",
    "url": "/tv/scifi-philosophical-tv/",
    "synopsis": "When 2% of the world's population abruptly disappears without explanation, the world struggles to understand just what they're supposed to do about it."
  },
  {
    "source": "tv",
    "refId": "1972",
    "title": "Battlestar Galactica",
    "seedName": "Battlestar Galactica",
    "creator": "",
    "year": "2004",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-1972.webp",
    "url": "/tv/scifi-philosophical-tv/",
    "synopsis": "When an old enemy, the Cylons, resurface and obliterate the 12 colonies, the crew of the aged Galactica protect a small civilian fleet - the last of humanity - as they journey toward the fabled 13th colony, Earth."
  },
  {
    "source": "tv",
    "refId": "42009",
    "title": "Black Mirror",
    "seedName": "Black Mirror",
    "creator": "",
    "year": "2011",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-42009.webp",
    "url": "/tv/scifi-philosophical-tv/",
    "synopsis": "Twisted tales run wild in this mind-bending anthology series that reveals humanity's worst traits, greatest innovations and more."
  },
  {
    "source": "tv",
    "refId": "69061",
    "title": "The OA",
    "seedName": "The OA",
    "creator": "",
    "year": "2016",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-69061.webp",
    "url": "/tv/scifi-philosophical-tv/",
    "synopsis": "Seven years after vanishing from her home, a young woman returns with mysterious new abilities and recruits five strangers for a secret mission."
  },
  {
    "source": "tv",
    "refId": "95396",
    "title": "Severance",
    "seedName": "Severance",
    "creator": "",
    "year": "2022",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-95396.webp",
    "url": "/tv/scifi-philosophical-tv/",
    "synopsis": "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. When a mysterious colleague appears outside of work, it begins a journey to discover the truth about their…"
  },
  {
    "source": "tv",
    "refId": "63247",
    "title": "Westworld",
    "seedName": "Westworld",
    "creator": "",
    "year": "2016",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-63247.webp",
    "url": "/tv/scifi-philosophical-tv/",
    "synopsis": "A dark odyssey about the dawn of artificial consciousness and the evolution of sin. Set at the intersection of the near future and the reimagined past, it explores a world in which every human appetite, no matter how noble or…"
  },
  {
    "source": "tv",
    "refId": "81349",
    "title": "Devs",
    "seedName": "Devs",
    "creator": "",
    "year": "2020",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-81349.webp",
    "url": "/tv/scifi-philosophical-tv/",
    "synopsis": "Young computer engineer Lily Chan investigates the secretive development division of her employer, a cutting-edge tech company based in San Francisco, which she believes is behind the murder of her boyfriend."
  },
  {
    "source": "tv",
    "refId": "90972",
    "title": "Station Eleven",
    "seedName": "Station Eleven",
    "creator": "",
    "year": "2021",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-90972.webp",
    "url": "/tv/scifi-philosophical-tv/",
    "synopsis": "The survivors of a devastating flu attempt to rebuild and reimagine the world anew – while holding on to the best of what’s been lost."
  },
  {
    "source": "tv",
    "refId": "1427",
    "title": "Broadchurch",
    "seedName": "Broadchurch",
    "creator": "",
    "year": "2013",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-1427.webp",
    "url": "/tv/slow-burn-crime/",
    "synopsis": "The murder of a young boy in a small coastal town brings a media frenzy, which threatens to tear the community apart."
  },
  {
    "source": "tv",
    "refId": "34415",
    "title": "The Killing",
    "seedName": "The Killing",
    "creator": "",
    "year": "2011",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-34415.webp",
    "url": "/tv/slow-burn-crime/",
    "synopsis": "The Killing is an American crime drama television series based upon the Danish television series Forbrydelsen. Set in Seattle, Washington, the series follows the various murder investigations by homicide detectives Sarah…"
  },
  {
    "source": "tv",
    "refId": "32368",
    "title": "The Killing",
    "seedName": "Forbrydelsen",
    "creator": "",
    "year": "2007",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-32368.webp",
    "url": "/tv/slow-burn-crime/",
    "synopsis": "The Killing is a Danish police procedural set in the Copenhagen main police department and revolves around Detective Inspector Sarah Lund and her team, with each season series following a different murder case day-by-day and a…"
  },
  {
    "source": "tv",
    "refId": "61555",
    "title": "The Missing",
    "seedName": "The Missing",
    "creator": "",
    "year": "2014",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-61555.webp",
    "url": "/tv/slow-burn-crime/",
    "synopsis": "A gripping anthological relationship thriller series exploring the emotional fallout of a child's abduction not only on the family but on the wider community, told over two time frames."
  },
  {
    "source": "tv",
    "refId": "61244",
    "title": "Happy Valley",
    "seedName": "Happy Valley",
    "creator": "",
    "year": "2014",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-61244.webp",
    "url": "/tv/slow-burn-crime/",
    "synopsis": "Happy Valley is a dark, funny, multi-layered thriller revolving around the personal and professional life of Catherine, a dedicated, experienced, hard-working copper."
  },
  {
    "source": "tv",
    "refId": "4588",
    "title": "ER",
    "seedName": "ER",
    "creator": "",
    "year": "1994",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-4588.webp",
    "url": "/tv/workplace-drama/",
    "synopsis": "ER explores the inner workings of an urban teaching hospital and the critical issues faced by the dedicated physicians and staff of its overburdened emergency room."
  },
  {
    "source": "tv",
    "refId": "136315",
    "title": "The Bear",
    "seedName": "The Bear",
    "creator": "",
    "year": "2022",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-136315.webp",
    "url": "/tv/workplace-drama/",
    "synopsis": "Carmy, a young fine-dining chef, comes home to Chicago to run his family sandwich shop. As he fights to transform the shop and himself, he works alongside a rough-around-the-edges crew that ultimately reveal themselves as his…"
  },
  {
    "source": "tv",
    "refId": "62649",
    "title": "Superstore",
    "seedName": "Superstore",
    "creator": "",
    "year": "2015",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-62649.webp",
    "url": "/tv/workplace-drama/",
    "synopsis": "A hilarious workplace comedy about a unique family of employees at a super-sized mega store. From the bright-eyed newbies and the seen-it-all veterans to the clueless summer hires and the in-it-for-life managers, together they…"
  },
  {
    "source": "tv",
    "refId": "61222",
    "title": "BoJack Horseman",
    "seedName": "BoJack Horseman",
    "creator": "",
    "year": "2014",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-61222.webp",
    "url": "/tv/animated-adult-tv/",
    "synopsis": "Meet the most beloved sitcom horse of the '90s , 20 years later. He's a curmudgeon with a heart of...not quite gold...but something like gold."
  },
  {
    "source": "tv",
    "refId": "60625",
    "title": "Rick and Morty",
    "seedName": "Rick and Morty",
    "creator": "",
    "year": "2013",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-60625.webp",
    "url": "/tv/animated-adult-tv/",
    "synopsis": "Follows a sociopathic genius scientist who drags his inherently timid grandson on adventures across the universe."
  },
  {
    "source": "tv",
    "refId": "456",
    "title": "The Simpsons",
    "seedName": "The Simpsons",
    "creator": "",
    "year": "1989",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-456.webp",
    "url": "/tv/animated-adult-tv/",
    "synopsis": "Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands."
  },
  {
    "source": "tv",
    "refId": "2190",
    "title": "South Park",
    "seedName": "South Park",
    "creator": "",
    "year": "1997",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-2190.webp",
    "url": "/tv/animated-adult-tv/",
    "synopsis": "Follow the misadventures of four irreverent grade-schoolers in the quiet, dysfunctional town of South Park, Colorado."
  },
  {
    "source": "tv",
    "refId": "10283",
    "title": "Archer",
    "seedName": "Archer",
    "creator": "",
    "year": "2009",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-10283.webp",
    "url": "/tv/animated-adult-tv/",
    "synopsis": "Smart-mouthed superspy Sterling Archer and his dysfunctional team of secret agents turn dangerous missions into messy misadventures around the globe."
  },
  {
    "source": "tv",
    "refId": "615",
    "title": "Futurama",
    "seedName": "Futurama",
    "creator": "",
    "year": "1999",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-615.webp",
    "url": "/tv/animated-adult-tv/",
    "synopsis": "The adventures of a late-20th-century New York City pizza delivery boy, Philip J. Fry, who, after being unwittingly cryogenically frozen for one thousand years, finds employment at Planet Express, an interplanetary delivery…"
  },
  {
    "source": "tv",
    "refId": "73021",
    "title": "Disenchantment",
    "seedName": "Disenchantment",
    "creator": "",
    "year": "2018",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-73021.webp",
    "url": "/tv/animated-adult-tv/",
    "synopsis": "Set in a ruined medieval city called Dreamland, Disenchantment follows the grubby adventures of a hard-drinking princess, her feisty elf companion and her personal demon."
  },
  {
    "source": "tv",
    "refId": "74387",
    "title": "Final Space",
    "seedName": "Final Space",
    "creator": "",
    "year": "2018",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-74387.webp",
    "url": "/tv/animated-adult-tv/",
    "synopsis": "An astronaut named Gary and his planet-destroying sidekick Mooncake embark on serialized journeys through space in order to unlock the mystery of “Final Space,” the last point in the universe, if it actually does exist."
  },
  {
    "source": "tv",
    "refId": "65494",
    "title": "The Crown",
    "seedName": "The Crown",
    "creator": "",
    "year": "2016",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-65494.webp",
    "url": "/tv/period-costume-tv/",
    "synopsis": "The gripping, decades-spanning inside story of Her Majesty Queen Elizabeth II and the Prime Ministers who shaped Britain's post-war destiny."
  },
  {
    "source": "tv",
    "refId": "33907",
    "title": "Downton Abbey",
    "seedName": "Downton Abbey",
    "creator": "",
    "year": "2010",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-33907.webp",
    "url": "/tv/period-costume-tv/",
    "synopsis": "A chronicle of the lives of the aristocratic Crawley family and their servants in the post-Edwardian era—with great events in history having an effect on their lives and on the British social hierarchy."
  },
  {
    "source": "tv",
    "refId": "56570",
    "title": "Outlander",
    "seedName": "Outlander",
    "creator": "",
    "year": "2014",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-56570.webp",
    "url": "/tv/period-costume-tv/",
    "synopsis": "The story of Claire Randall, a married combat nurse from 1945 who is mysteriously swept back in time to 1743, where she is immediately thrown into an unknown world where her life is threatened."
  },
  {
    "source": "tv",
    "refId": "62084",
    "title": "Poldark",
    "seedName": "Poldark",
    "creator": "",
    "year": "2015",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-62084.webp",
    "url": "/tv/period-costume-tv/",
    "synopsis": "Britain is in the grip of a chilling recession... falling wages, rising prices, civil unrest - only the bankers are smiling."
  },
  {
    "source": "tv",
    "refId": "61697",
    "title": "Wolf Hall",
    "seedName": "Wolf Hall",
    "creator": "",
    "year": "2015",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-61697.webp",
    "url": "/tv/period-costume-tv/",
    "synopsis": "England in the 1520s is a heartbeat from disaster. If the King dies without a male heir, the country could be destroyed by civil war."
  },
  {
    "source": "tv",
    "refId": "91239",
    "title": "Bridgerton",
    "seedName": "Bridgerton",
    "creator": "",
    "year": "2020",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-91239.webp",
    "url": "/tv/period-costume-tv/",
    "synopsis": "Wealth, lust, and betrayal set in the backdrop of Regency era England, seen through the eyes of the powerful Bridgerton family."
  },
  {
    "source": "tv",
    "refId": "81723",
    "title": "The Gilded Age",
    "seedName": "The Gilded Age",
    "creator": "",
    "year": "2022",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-81723.webp",
    "url": "/tv/period-costume-tv/",
    "synopsis": "It’s 1882 and the Gilded Age is in full swing when Marian Brook, a young orphaned daughter of a Southern general, moves in with her rigidly conventional aunts in New York City."
  },
  {
    "source": "tv",
    "refId": "1101",
    "title": "My So-Called Life",
    "seedName": "My So-Called Life",
    "creator": "",
    "year": "1994",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-1101.webp",
    "url": "/tv/teen-angst-smart/",
    "synopsis": "The life of a 15 year-old high school student, whose angst-ridden journey through adolescence, friendship, parents, and life teaches her what it means to grow up."
  },
  {
    "source": "tv",
    "refId": "2382",
    "title": "Freaks and Geeks",
    "seedName": "Freaks and Geeks",
    "creator": "",
    "year": "1999",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-2382.webp",
    "url": "/tv/teen-angst-smart/",
    "synopsis": "High school mathlete Lindsay Weir rebels and begins hanging out with a crowd of burnouts (the \"freaks\"), while her brother Sam Weir navigates a different part of the social universe with his nerdy friends (the \"geeks\")."
  },
  {
    "source": "tv",
    "refId": "85552",
    "title": "Euphoria",
    "seedName": "Euphoria",
    "creator": "",
    "year": "2019",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-85552.webp",
    "url": "/tv/teen-angst-smart/",
    "synopsis": "A group of high school students navigate love and friendships in a world of drugs, sex, trauma, and social media."
  },
  {
    "source": "tv",
    "refId": "65345",
    "title": "The Get Down",
    "seedName": "The Get Down",
    "creator": "",
    "year": "2016",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-65345.webp",
    "url": "/tv/teen-angst-smart/",
    "synopsis": "In 1977 New York City, the talented and soulful youth of the South Bronx chase dreams and breakneck beats to transform music history."
  },
  {
    "source": "tv",
    "refId": "900",
    "title": "Skins",
    "seedName": "Skins",
    "creator": "",
    "year": "2007",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-900.webp",
    "url": "/tv/teen-angst-smart/",
    "synopsis": "Irreverent comedy drama which follows the messy lives, loves, delirious highs and inevitable lows of a group of raucous teenage friends in Bristol."
  },
  {
    "source": "tv",
    "refId": "1948",
    "title": "Degrassi",
    "seedName": "Degrassi",
    "creator": "",
    "year": "2001",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-1948.webp",
    "url": "/tv/teen-angst-smart/",
    "synopsis": "The life of a group of adolescents going through the trials and tribulations of teendom at Degrassi Community School."
  },
  {
    "source": "tv",
    "refId": "81356",
    "title": "Sex Education",
    "seedName": "Sex Education",
    "creator": "",
    "year": "2019",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-81356.webp",
    "url": "/tv/teen-angst-smart/",
    "synopsis": "Inexperienced Otis channels his sex therapist mom when he teams up with rebellious Maeve to set up an underground sex therapy clinic at school."
  },
  {
    "source": "tv",
    "refId": "76148",
    "title": "Derry Girls",
    "seedName": "Derry Girls",
    "creator": "",
    "year": "2018",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-76148.webp",
    "url": "/tv/teen-angst-smart/",
    "synopsis": "Amidst the political conflict of Northern Ireland in the 1990s, five secondary school students square off with the universal challenges of being a teenager."
  },
  {
    "source": "tv",
    "refId": "1920",
    "title": "Twin Peaks",
    "seedName": "Twin Peaks",
    "creator": "",
    "year": "1990",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-1920.webp",
    "url": "/tv/cult-weird-tv/",
    "synopsis": "The body of Laura Palmer is washed up on a beach near the small Washington state town of Twin Peaks. FBI Special Agent Dale Cooper is called in to investigate her strange demise only to uncover a web of mystery that ultimately…"
  },
  {
    "source": "tv",
    "refId": "4087",
    "title": "The X-Files",
    "seedName": "The X-Files",
    "creator": "",
    "year": "1993",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-4087.webp",
    "url": "/tv/cult-weird-tv/",
    "synopsis": "The exploits of FBI Special Agents Fox Mulder and Dana Scully who investigate X-Files: marginalized, unsolved cases involving paranormal phenomena."
  },
  {
    "source": "tv",
    "refId": "1437",
    "title": "Firefly",
    "seedName": "Firefly",
    "creator": "",
    "year": "2002",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-1437.webp",
    "url": "/tv/cult-weird-tv/",
    "synopsis": "In the year 2517, the universe is a vast frontier where lawlessness reigns and adventure awaits! Join Captain Malcolm Reynolds and his ragtag crew aboard the spaceship Serenity as they navigate the fringes of society, battling…"
  },
  {
    "source": "tv",
    "refId": "67195",
    "title": "Legion",
    "seedName": "Legion",
    "creator": "",
    "year": "2017",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-67195.webp",
    "url": "/tv/cult-weird-tv/",
    "synopsis": "David Haller, AKA Legion, is a troubled young man who may be more than human. Diagnosed as schizophrenic, David has been in and out of psychiatric hospitals for years."
  },
  {
    "source": "tv",
    "refId": "38215",
    "title": "Dirk Gently",
    "seedName": "Dirk Gently",
    "creator": "",
    "year": "2012",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-38215.webp",
    "url": "/tv/cult-weird-tv/",
    "synopsis": "Detective Dirk Gently operates based on the fundamental interconnectedness of all things."
  },
  {
    "source": "tv",
    "refId": "61664",
    "title": "Sense8",
    "seedName": "Sense8",
    "creator": "",
    "year": "2015",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-61664.webp",
    "url": "/tv/cult-weird-tv/",
    "synopsis": "One gunshot, one death, one moment out of time that irrevocably links eight minds in disparate parts of the world, putting them in each other's lives, each other's secrets, and in terrible danger."
  },
  {
    "source": "tv",
    "refId": "84958",
    "title": "Loki",
    "seedName": "Loki",
    "creator": "",
    "year": "2021",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-84958.webp",
    "url": "/tv/cult-weird-tv/",
    "synopsis": "After stealing the Tesseract during the events of “Avengers: Endgame,” an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and…"
  },
  {
    "source": "tv",
    "refId": "61929",
    "title": "The Jinx",
    "seedName": "The Jinx",
    "creator": "",
    "year": "2015",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-61929.webp",
    "url": "/tv/documentary-series/",
    "synopsis": "Robert Durst, scion of NY's billionaire real-estate family, has been accused of three murders but has evaded justice for over 30 years."
  },
  {
    "source": "tv",
    "refId": "64439",
    "title": "Making a Murderer",
    "seedName": "Making a Murderer",
    "creator": "",
    "year": "2015",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-64439.webp",
    "url": "/tv/documentary-series/",
    "synopsis": "Filmed over 10 years, this real-life thriller follows a DNA exoneree who, while exposing police corruption, becomes a suspect in a grisly new crime."
  },
  {
    "source": "tv",
    "refId": "77601",
    "title": "Wild Wild Country",
    "seedName": "Wild Wild Country",
    "creator": "",
    "year": "2018",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-77601.webp",
    "url": "/tv/documentary-series/",
    "synopsis": "When a controversial cult leader builds a utopian city in the Oregon desert, conflict with the locals escalates into a national scandal."
  },
  {
    "source": "tv",
    "refId": "122196",
    "title": "The Staircase",
    "seedName": "The Staircase",
    "creator": "",
    "year": "2022",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-122196.webp",
    "url": "/tv/documentary-series/",
    "synopsis": "An exploration of the life of Michael Peterson, his sprawling North Carolina family, and the suspicious death of his wife, Kathleen Peterson."
  },
  {
    "source": "tv",
    "refId": "100698",
    "title": "Tiger King",
    "seedName": "Tiger King",
    "creator": "",
    "year": "2020",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-100698.webp",
    "url": "/tv/documentary-series/",
    "synopsis": "A zoo owner spirals out of control amid a cast of eccentric characters in this true murder-for-hire story from the underworld of big cat breeding."
  },
  {
    "source": "tv",
    "refId": "26101",
    "title": "The Keepers",
    "seedName": "The Keepers",
    "creator": "",
    "year": "2017",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-26101.webp",
    "url": "/tv/documentary-series/",
    "synopsis": "This docuseries examines the decades-old murder of Sister Catherine Cesnik and its suspected link to a priest accused of abuse."
  },
  {
    "source": "tv",
    "refId": "21220",
    "title": "Father Matteo",
    "seedName": "Don",
    "creator": "",
    "year": "2000",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-21220.webp",
    "url": "/tv/documentary-series/",
    "synopsis": "Don Matteo is a thoroughly ordinary Catholic priest with an extraordinary ability to read people and solve crimes. He’s a parish priest who never met an unjustly accused person he didn’t want to help."
  },
  {
    "source": "tv",
    "refId": "49920",
    "title": "The Vow",
    "seedName": "The Vow",
    "creator": "",
    "year": "2020",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-49920.webp",
    "url": "/tv/documentary-series/",
    "synopsis": "The docuseries follows people deeply involved in the group NXIVM — which is faced with various charges, including sex trafficking and racketeering conspiracy — over the course of several years."
  },
  {
    "source": "tv",
    "refId": "4546",
    "title": "Curb Your Enthusiasm",
    "seedName": "Curb Your Enthusiasm",
    "creator": "",
    "year": "2000",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-4546.webp",
    "url": "/tv/comedy-of-cringe-tv/",
    "synopsis": "The off-kilter, unscripted comic vision of Larry David, who plays himself in a parallel universe in which he can't seem to do anything right, and, by his standards, neither can anyone else."
  },
  {
    "source": "tv",
    "refId": "87382",
    "title": "Ramy",
    "seedName": "Ramy",
    "creator": "",
    "year": "2019",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-87382.webp",
    "url": "/tv/comedy-of-cringe-tv/",
    "synopsis": "Ramy, the son of Egyptian immigrants, is on a spiritually conflicting journey in his New Jersey neighborhood, pulled between his Muslim community that thinks life is a constant test, his millennial friends who think life is…"
  },
  {
    "source": "tv",
    "refId": "83631",
    "title": "What We Do in the Shadows",
    "seedName": "What We Do",
    "creator": "",
    "year": "2019",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-83631.webp",
    "url": "/tv/comedy-of-cringe-tv/",
    "synopsis": "A documentary-style look into the daily (or rather, nightly) lives of a group of vampires in Staten Island who have “lived” together for hundreds and hundreds of years."
  },
  {
    "source": "tv",
    "refId": "64551",
    "title": "Baskets",
    "seedName": "Baskets",
    "creator": "",
    "year": "2016",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-64551.webp",
    "url": "/tv/comedy-of-cringe-tv/",
    "synopsis": "Chip Baskets wants to follow his dream of being a French clown—however, reality keeps interfering. Saddled with financial difficulties and facing an impenetrable language barrier, he moves back home to Bakersfield with high hopes."
  },
  {
    "source": "tv",
    "refId": "204284",
    "title": "The Rehearsal",
    "seedName": "The Rehearsal",
    "creator": "",
    "year": "2022",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-204284.webp",
    "url": "/tv/comedy-of-cringe-tv/",
    "synopsis": "With a construction crew, a legion of actors, and seemingly unlimited resources, Nathan Fielder allows ordinary people to prepare for life's biggest moments by \"rehearsing\" them in carefully crafted simulations of his own design."
  },
  {
    "source": "tv",
    "refId": "5291",
    "title": "Homicide",
    "seedName": "Homicide",
    "creator": "",
    "year": "1964",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-5291.webp",
    "url": "/tv/police-procedural-subverted/",
    "synopsis": "Homicide was an Australian television police drama series The series dealt with the homicide squad of the Victorian Police force and the various crimes and cases the detectives are called upon to investigate."
  },
  {
    "source": "tv",
    "refId": "48891",
    "title": "Brooklyn Nine-Nine",
    "seedName": "Brooklyn Nine-Nine",
    "creator": "",
    "year": "2013",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-48891.webp",
    "url": "/tv/police-procedural-subverted/",
    "synopsis": "A single-camera ensemble comedy following the lives of an eclectic group of detectives in a New York precinct, including one slacker who is forced to shape up when he gets a new boss."
  },
  {
    "source": "tv",
    "refId": "46648",
    "title": "True Detective",
    "seedName": "True Detective",
    "creator": "",
    "year": "2014",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-46648.webp",
    "url": "/tv/police-procedural-subverted/",
    "synopsis": "An American anthology police detective series utilizing multiple timelines in which investigations seem to unearth personal and professional secrets of those involved, both within or outside the law."
  },
  {
    "source": "tv",
    "refId": "17611",
    "title": "Southland",
    "seedName": "Southland",
    "creator": "",
    "year": "2009",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-17611.webp",
    "url": "/tv/police-procedural-subverted/",
    "synopsis": "A raw and authentic look into the Los Angeles crime scene, going far inside the lives of cops, criminals, victims and their families."
  },
  {
    "source": "tv",
    "refId": "60585",
    "title": "Bosch",
    "seedName": "Bosch",
    "creator": "",
    "year": "2015",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-60585.webp",
    "url": "/tv/police-procedural-subverted/",
    "synopsis": "Harry Bosch, an LAPD homicide detective, stands trial for the fatal shooting of a serial murder suspect. A cold case involving the remains of a missing boy forces Bosch to confront his past."
  },
  {
    "source": "tv",
    "refId": "1399",
    "title": "Game of Thrones",
    "seedName": "Game of Thrones",
    "creator": "",
    "year": "2011",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-1399.webp",
    "url": "/tv/fantasy-epic-tv/",
    "synopsis": "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war."
  },
  {
    "source": "tv",
    "refId": "84773",
    "title": "The Lord of the Rings: The Rings of Power",
    "seedName": "The Lord of the Rings",
    "creator": "",
    "year": "2022",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-84773.webp",
    "url": "/tv/fantasy-epic-tv/",
    "synopsis": "Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth."
  },
  {
    "source": "tv",
    "refId": "68507",
    "title": "His Dark Materials",
    "seedName": "His Dark Materials",
    "creator": "",
    "year": "2019",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-68507.webp",
    "url": "/tv/fantasy-epic-tv/",
    "synopsis": "Lyra is an orphan who lives in a parallel universe in which science, theology and magic are entwined. Her search for a kidnapped friend uncovers a sinister plot involving stolen children and turns into a quest to understand a…"
  },
  {
    "source": "tv",
    "refId": "71912",
    "title": "The Witcher",
    "seedName": "The Witcher",
    "creator": "",
    "year": "2019",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-71912.webp",
    "url": "/tv/fantasy-epic-tv/",
    "synopsis": "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts."
  },
  {
    "source": "tv",
    "refId": "90027",
    "title": "Carnival Row",
    "seedName": "Carnival Row",
    "creator": "",
    "year": "2019",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-90027.webp",
    "url": "/tv/fantasy-epic-tv/",
    "synopsis": "In a mystical and dark city filled with humans, fairies and other creatures, a police detective investigates a series of gruesome murders leveled against the fairy population."
  },
  {
    "source": "tv",
    "refId": "71914",
    "title": "The Wheel of Time",
    "seedName": "The Wheel of Time",
    "creator": "",
    "year": "2021",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-71914.webp",
    "url": "/tv/fantasy-epic-tv/",
    "synopsis": "The lives of five young villagers change forever when a strange and powerful woman arrives, claiming one of them is the child of an ancient prophecy with the power to tip the balance between Light and Dark forever."
  },
  {
    "source": "tv",
    "refId": "93740",
    "title": "Foundation",
    "seedName": "Foundation",
    "creator": "",
    "year": "2021",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-93740.webp",
    "url": "/tv/fantasy-epic-tv/",
    "synopsis": "Follow a band of exiles on their monumental journey to save humanity and rebuild civilization amid the fall of the Galactic Empire."
  },
  {
    "source": "tv",
    "refId": "46639",
    "title": "American Gods",
    "seedName": "American Gods",
    "creator": "",
    "year": "2017",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-46639.webp",
    "url": "/tv/fantasy-epic-tv/",
    "synopsis": "An ex-con becomes the traveling partner of a conman who turns out to be one of the older gods trying to recruit troops to battle the upstart deities."
  },
  {
    "source": "tv",
    "refId": "72750",
    "title": "Killing Eve",
    "seedName": "Killing Eve",
    "creator": "",
    "year": "2018",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-72750.webp",
    "url": "/tv/female-led-drama/",
    "synopsis": "A security consultant hunts for a ruthless assassin. Equally obsessed with each other, they go head to head in an epic game of cat-and-mouse."
  },
  {
    "source": "tv",
    "refId": "66292",
    "title": "Big Little Lies",
    "seedName": "Big Little Lies",
    "creator": "",
    "year": "2017",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-66292.webp",
    "url": "/tv/female-led-drama/",
    "synopsis": "The tale of three mothers of first graders whose apparently perfect lives unravel to the point of murder."
  },
  {
    "source": "tv",
    "refId": "69478",
    "title": "The Handmaid's Tale",
    "seedName": "The Handmaid",
    "creator": "",
    "year": "2017",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-69478.webp",
    "url": "/tv/female-led-drama/",
    "synopsis": "Set in a dystopian future, a woman is forced to live as a concubine under a fundamentalist theocratic dictatorship."
  },
  {
    "source": "tv",
    "refId": "90282",
    "title": "The Morning Show",
    "seedName": "The Morning Show",
    "creator": "",
    "year": "2019",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-90282.webp",
    "url": "/tv/female-led-drama/",
    "synopsis": "A behind-the-scenes look at the lives of the people who help America wake up in the morning, exploring the unique challenges faced by the men and women who carry out this daily televised ritual."
  },
  {
    "source": "tv",
    "refId": "203857",
    "title": "The Diplomat",
    "seedName": "The Diplomat",
    "creator": "",
    "year": "2023",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-203857.webp",
    "url": "/tv/female-led-drama/",
    "synopsis": "Amid an international crisis, a US diplomat contends with her high-profile job as ambassador to the UK and her strained marriage to a political star."
  },
  {
    "source": "tv",
    "refId": "81357",
    "title": "Dead to Me",
    "seedName": "Dead to Me",
    "creator": "",
    "year": "2019",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-81357.webp",
    "url": "/tv/female-led-drama/",
    "synopsis": "A hotheaded widow searching for the hit-and-run driver who mowed down her husband befriends an eccentric optimist who isn't quite what she seems."
  },
  {
    "source": "tv",
    "refId": "73107",
    "title": "Barry",
    "seedName": "Barry",
    "creator": "",
    "year": "2018",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-73107.webp",
    "url": "/tv/dark-comedy-tv/",
    "synopsis": "A hit man from the Midwest moves to Los Angeles and gets caught up in the city's theatre arts scene."
  },
  {
    "source": "tv",
    "refId": "197406",
    "title": "Life After Life",
    "seedName": "After Life",
    "creator": "",
    "year": "2022",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-197406.webp",
    "url": "/tv/dark-comedy-tv/",
    "synopsis": "If you could live your life time and again, would you ever get it right? Ursula dies and is reborn, living through turbulent times - but what is it she needs to stay alive for?"
  },
  {
    "source": "tv",
    "refId": "84977",
    "title": "Russian Doll",
    "seedName": "Russian Doll",
    "creator": "",
    "year": "2019",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-84977.webp",
    "url": "/tv/dark-comedy-tv/",
    "synopsis": "Nadia keeps dying and reliving her 36th birthday party. She's trapped in a surreal time loop -- and staring down the barrel of her own mortality."
  },
  {
    "source": "tv",
    "refId": "233045",
    "title": "Santos",
    "seedName": "Santos",
    "creator": "",
    "year": "2023",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-233045.webp",
    "url": "/tv/dark-comedy-tv/",
    "synopsis": "Love couple Glenn and Yola are trying to build a life in Rotterdam. Although they both pursue their dreams, they find themselves stuck between their own ambitions and their criminal friends and family."
  },
  {
    "source": "tv",
    "refId": "71446",
    "title": "Money Heist",
    "seedName": "Money Heist",
    "creator": "",
    "year": "2017",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-71446.webp",
    "url": "/tv/foreign-language-gems/",
    "synopsis": "To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose."
  },
  {
    "source": "tv",
    "refId": "70523",
    "title": "Dark",
    "seedName": "Dark",
    "creator": "",
    "year": "2017",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-70523.webp",
    "url": "/tv/foreign-language-gems/",
    "synopsis": "A missing child sets four families on a frantic hunt for answers as they unearth a mind-bending mystery that spans three generations."
  },
  {
    "source": "tv",
    "refId": "42445",
    "title": "Borgen",
    "seedName": "Borgen",
    "creator": "",
    "year": "2010",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-42445.webp",
    "url": "/tv/foreign-language-gems/",
    "synopsis": "40-year old political leader Birgitte Nyborg secures her party a landslide victory through her idealism and huge effort, then faces the biggest challenge of her life: how most effectively to use the newly won seats, and how…"
  },
  {
    "source": "tv",
    "refId": "96677",
    "title": "Lupin",
    "seedName": "Lupin",
    "creator": "",
    "year": "2021",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-96677.webp",
    "url": "/tv/foreign-language-gems/",
    "synopsis": "Inspired by the adventures of Arsène Lupin, gentleman thief Assane Diop sets out to avenge his father for an injustice inflicted by a wealthy family."
  },
  {
    "source": "tv",
    "refId": "76669",
    "title": "Elite",
    "seedName": "Elite",
    "creator": "",
    "year": "2018",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-76669.webp",
    "url": "/tv/foreign-language-gems/",
    "synopsis": "When three working class kids enroll in the most exclusive school in Spain, the clash between the wealthy and the poor students leads to tragedy."
  },
  {
    "source": "tv",
    "refId": "93405",
    "title": "Squid Game",
    "seedName": "Squid Game",
    "creator": "",
    "year": "2021",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-93405.webp",
    "url": "/tv/foreign-language-gems/",
    "synopsis": "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits — with deadly high stakes."
  },
  {
    "source": "tv",
    "refId": "14658",
    "title": "Survivor",
    "seedName": "Survivor",
    "creator": "",
    "year": "2000",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-14658.webp",
    "url": "/tv/reality-game/"
  },
  {
    "source": "tv",
    "refId": "30957",
    "title": "The Amazing Race",
    "seedName": "The Amazing Race",
    "creator": "",
    "year": "2001",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-30957.webp",
    "url": "/tv/reality-game/"
  },
  {
    "source": "tv",
    "refId": "8514",
    "title": "RuPaul's Drag Race",
    "seedName": "RuPaul Drag Race",
    "creator": "",
    "year": "2009",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-8514.webp",
    "url": "/tv/reality-game/",
    "synopsis": "Join RuPaul, the world's most famous drag queen, as the host, mentor and judge for the ultimate in drag queen competitions. The top drag queens in the U.S."
  },
  {
    "source": "tv",
    "refId": "87012",
    "title": "The Great British Bake Off",
    "seedName": "The Great British Bake Off",
    "creator": "",
    "year": "2017",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-87012.webp",
    "url": "/tv/reality-game/",
    "synopsis": "Britain's best amateur bakers compete in the iconic white tent - all united in their aim to prove their baking skills and impress judges Paul Hollywood and Prue Leith."
  },
  {
    "source": "tv",
    "refId": "63404",
    "title": "Taskmaster",
    "seedName": "Taskmaster",
    "creator": "",
    "year": "2015",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-63404.webp",
    "url": "/tv/reality-game/",
    "synopsis": "Greg Davies is the Taskmaster, and with the help of his ever-loyal assistant Alex Horne, they will set out to test the wiles, wit, wisdom and skills of five hyper-competitive comedians."
  },
  {
    "source": "tv",
    "refId": "58832",
    "title": "Naked and Afraid",
    "seedName": "Naked and Afraid",
    "creator": "",
    "year": "2013",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-58832.webp",
    "url": "/tv/reality-game/",
    "synopsis": "What happens when you put two complete strangers - sans clothes - in some of the most extreme environments on Earth? Each male-female duo is left with no food, no water, no clothes, and only one survival item each as they…"
  },
  {
    "source": "tv",
    "refId": "41822",
    "title": "Top Chef",
    "seedName": "Top Chef",
    "creator": "",
    "year": "2006",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-41822.webp",
    "url": "/tv/reality-game/",
    "synopsis": "An American reality competition show in which chefs compete against each other in culinary challenges and are judged by a panel of professional chefs and other notables from the food and wine industry with one or more…"
  },
  {
    "source": "tv",
    "refId": "215943",
    "title": "The Traitors",
    "seedName": "The Traitors",
    "creator": "",
    "year": "2023",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-215943.webp",
    "url": "/tv/reality-game/",
    "synopsis": "The entertainment industry’s most competitive reality stars and famous faces play the ultimate murder mystery game. Hosted by award-winning actor Alan Cumming at an ancient castle set deep in the Scottish Highlands,…"
  },
  {
    "source": "tv",
    "refId": "79788",
    "title": "Watchmen",
    "seedName": "Watchmen",
    "creator": "",
    "year": "2019",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-79788.webp",
    "url": "/tv/superhero-deconstructed/",
    "synopsis": "Set in an alternate history where “superheroes” are treated as outlaws, “Watchmen” embraces the nostalgia of the original groundbreaking graphic novel while attempting to break new ground of its own."
  },
  {
    "source": "tv",
    "refId": "76479",
    "title": "The Boys",
    "seedName": "The Boys",
    "creator": "",
    "year": "2019",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-76479.webp",
    "url": "/tv/superhero-deconstructed/",
    "synopsis": "A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty."
  },
  {
    "source": "tv",
    "refId": "202555",
    "title": "Daredevil: Born Again",
    "seedName": "Daredevil",
    "creator": "",
    "year": "2025",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-202555.webp",
    "url": "/tv/superhero-deconstructed/",
    "synopsis": "Matt Murdock, a blind lawyer with heightened abilities, is fighting for justice through his bustling law firm, while former mob boss Wilson Fisk pursues his own political endeavors in New York."
  },
  {
    "source": "tv",
    "refId": "38472",
    "title": "Marvel's Jessica Jones",
    "seedName": "Jessica Jones",
    "creator": "",
    "year": "2015",
    "tags": [
      "tv"
    ],
    "cover": "/images/tv/tv-38472.webp",
    "url": "/tv/superhero-deconstructed/",
    "synopsis": "After a tragic ending to her short-lived super hero stint, Jessica Jones is rebuilding her personal life and career as a detective who gets pulled into cases involving people with extraordinary abilities in New York City."
  }
];
