// 音乐策展专题种子（50 条）
// 条目名种子：专辑名 / 艺术家名（构建期由 MusicBrainz 解析为元数据+封面）
// editorial thesis 改编自豆瓣/网易云歌单策展逻辑，精细翻译+改写避免被判重复
import type { CurationTheme } from './curation';

export const MUSIC_THEMES: CurationTheme[] = [
  {
    slug: 'late-night-focus-lofi',
    channel: 'music',
    title: 'Late-Night Focus: Lo-Fi & Ambient',
    thesis:
      'These records share one job — to disappear. We picked albums engineered for background concentration, where texture beats melody and nothing demands your attention.',
    intro: 'A curated descent into instrumental calm. Perfect for 1am deadlines and empty rooms.',
    audience:
      'This list is for the 1am worker, the insomniac who\'s productive, and anyone who needs sound that doesn\'t ask for attention. You\'ll like it if lyrics pull you out of your own thoughts, or if a silent room makes your brain louder. Skip it if you actually want to listen — this is wallpaper on purpose, and people who crave a chorus will find it frustrating. It\'s also a reliable tool for focus sessions where familiarity crowds out the urge to switch tabs.',
    criteria:
      'We excluded anything with a vocal hook that competes for language, any drop designed to jolt, and any track that "builds" toward a payoff you have to wait for. We kept records engineered to recede: ambient, lo-fi, and instrumental electronic where texture beats melody. A pick earned its place by disappearing behind your actual task. Where two made the same point, we kept the one least likely to interrupt a sentence.',
    alternatives:
      'If the calm is right but you want it warmer, Rain on the Window keeps you company while you work. If you want the same focus with more energy to start, Adrenaline Night is the wrong speed — this is the opposite. People who need a plot should look at the film and TV themes instead. For pure melancholy without the productivity angle, The Lonely Tuesday.',
    faq: [
      { q: 'Why no vocals?', a: 'Because sung words compete with the language centers you\'re using to work or read. Instrumental and ambient let the brain stay on the task.' },
      { q: 'Is this the same as a "study playlist"?', a: 'Closer to a focus tool. We curated for disappearance, not for a vibe you\'d notice — the goal is that you forget it\'s on.' },
      { q: 'Can I loop one album all night?', a: 'That\'s the ideal use. Music for Airports was literally designed to be ignorable for hours.' },
      { q: 'What if I need energy to start?', a: 'Then start with Adrenaline Night, then land here once you\'re moving.' },
      { q: 'Where does the metadata come from?', a: 'MusicBrainz (CC0) for real credits and covers; the "why this helps you focus" writing is ours.' },
    ],
    related: ['focus-flow', 'rainy-window', 'lonely-tuesday'],
    tags: ['ambient', 'lofi', 'electronic', 'focused'],
    mood: ['focused', 'relaxed'],
    items: ['Music for Airports', 'Selected Ambient Works 85-92', 'Dreamland', 'Innervisions', 'Teardrop', 'Weightless', 'Ambient 1', 'Blonde'],
  },
  {
    slug: 'british-indie-90s',
    channel: 'music',
    title: 'The 90s British Indie Wave',
    thesis:
      'Not Britpop-as-headline, but the quieter guitar bands that made melancholy sound like sunshine. A lineage from shoegaze to kitchen-sink romance.',
    intro: 'Baggy trousers, reverbed guitars, and a specific kind of northern sadness.',
    audience:
      'This list is for people who like their sadness with a melody, and their melodies with a little rain on them. You\'ll like it if you grew up on British guitar music, or if you discovered that melancholy sounds better with a northern accent and a reverb pedal. Skip it if you need uptempo energy — this is a list for grey days and longer drives, not the dancefloor. It\'s also a soft entry point for anyone exploring "indie" as a feeling rather than a genre tag.',
    criteria:
      'We excluded the headline Britpop singles everyone knows and kept the quieter lineage underneath: shoegaze, kitchen-sink romance, and the bands that made restraint sound like a virtue. We prioritized songs where the sadness is dressed as sunshine — the specific trick this scene perfected. A pick earned its place by sounding like a specific nowhere town at 4pm. Where two made the same point, we kept the more textural one.',
    alternatives:
      'If the melancholy is right but you want it colder, The Lonely Tuesday strips the warmth out. If you want the British feeling in another medium, the neo-noir and slow-burn TV themes carry the same grey light. People who find this "too polite" should try Adrenaline Night. For the cozy indoor version, Rain on the Window.',
    faq: [
      { q: 'Is this just Britpop?', a: 'Deliberately not. We skipped the big singles and kept the quieter guitar bands — shoegaze and kitchen-sink romance — that made the era\'s sadness sound like sunshine.' },
      { q: 'Do I need to be British to like it?', a: 'Not at all. The feeling travels. If you like reverb, minor chords, and a sense of place, you\'re the audience.' },
      { q: 'Why these specific bands over the famous ones?', a: 'Because fame is easy to find elsewhere. We curate for the argument a list makes, so lesser-known entries that prove the point outrank obvious hits.' },
      { q: 'Where do the covers and credits come from?', a: 'MusicBrainz (CC0). The editorial reason each band belongs is ours.' },
      { q: 'Can I generate a similar list?', a: 'Yes — the Playlist Generator lets you set mood and genre and assemble a starter set with the same logic.' },
    ],
    related: ['lonely-tuesday', 'rainy-window', 'golden-hour-drive'],
    tags: ['indie', 'rock', '1990s', 'british'],
    mood: ['melancholy', 'relaxed'],
    items: ['The Bends', 'His and Hers', 'The Queen Is Dead', 'Loveless', 'Parklife', 'Crooked Rain', 'Girls & Boys', 'Ride Nowhere'],
  },
  {
    slug: 'cosmic-jazz',
    channel: 'music',
    title: 'Cosmic Jazz: From Blue Note to the Stars',
    thesis:
      'Jazz that left the club and went orbital. We trace the spiritual, modal, and free strands that treated improvisation as propulsion.',
    intro: 'Modal scales, open skies, and the long solo as a vehicle.',
    tags: ['jazz', '1970s', 'instrumental'],
    mood: ['focused', 'relaxed'],
    items: ['A Love Supreme', 'Kind of Blue', 'Head Hunters', 'Bitches Brew', 'The QE2', 'On the Corner', 'In a Silent Way', 'Blue Train'],
  },
  {
    slug: 'hiphop-storytelling',
    channel: 'music',
    title: 'Hip-Hop as Novel: The Storytellers',
    thesis:
      'Concept albums and narrative verses where the bar is the sentence. We favor the writers who built worlds over the ones who filled hooks.',
    intro: 'Concrete imagery, recurring characters, and the album as a book.',
    tags: ['hiphop', '2010s', 'lyrical'],
    mood: ['energetic'],
    items: ['good kid, m.A.A.d city', 'To Pimp a Butterfly', 'Illmatic', 'Ready to Die', 'The College Dropout', 'Food & Liquor', 'Section.80', 'Damn'],
  },
  {
    slug: 'classical-rainy-window',
    channel: 'music',
    title: 'Classical for a Rainy Window',
    thesis:
      'Romantic-era piano and string works chosen for weather, not canon. The point is the room you are sitting in, not the conservatory.',
    intro: 'Slow movements, minor keys, and the sound of water on glass.',
    tags: ['classical', 'piano', 'romantic'],
    mood: ['melancholy', 'relaxed'],
    items: ['Clair de Lune', 'Gymnopedie', 'Moonlight Sonata', 'Nocturnes Op.9', 'The Four Seasons', 'Prelude in C', 'Spiegel im Spiegel', 'Recomposed'],
  },
  {
    slug: 'detroit-techno-origin',
    channel: 'music',
    title: 'Detroit Techno: The Belleville Three',
    thesis:
      'Before techno was a festival, it was three friends in a Michigan basement imagining a future that sounded like machinery and hope.',
    intro: 'Roland drum machines, factory rhythms, and a city dreaming in code.',
    tags: ['techno', 'electronic', '1980s', 'detroit'],
    mood: ['energetic', 'focused'],
    items: ['Model 500', 'Inner City', 'Strings of Life', 'Techno Music', 'Beyond the Dance', 'Nude Photo', 'Big Fun', 'Cybotron'],
  },
  {
    slug: 'brazilian-bossa',
    channel: 'music',
    title: 'Bossa Nova: Quiet Revolution',
    thesis:
      'A genre built on restraint — soft vowels, nylon strings, and the radical idea that sophistication could also be tender.',
    intro: 'Rio apartments, sea breeze, and the unhurried conversation of guitar and voice.',
    tags: ['bossa', 'latin', '1960s', 'acoustic'],
    mood: ['relaxed'],
    items: ['Getz/Gilberto', 'Chega de Saudade', 'Wave', 'Francis Albert Sinatra', 'A Certain Smile', 'Joao Gilberto', 'Amoroso', 'Bossa Nova'],
  },
  {
    slug: 'post-punk-uk',
    channel: 'music',
    title: 'Post-Punk: Angular and Cold',
    thesis:
      'When punk ate art school. We collect the bands that turned dissonance, monotone, and dub bass into a new kind of elegance.',
    intro: 'Leather, repetition, and the rhythm section as the whole argument.',
    tags: ['postpunk', 'rock', '1980s', 'uk'],
    mood: ['melancholy'],
    items: ['Unknown Pleasures', 'Closer', 'Fire of Love', 'Metal Box', 'Germfree Adolescents', 'Entertainment', 'Juju', 'In the Flat Field'],
  },
  {
    slug: 'synthwave-retro',
    channel: 'music',
    title: 'Synthwave: Neon Nostalgia',
    thesis:
      'A genre that treats the 1980s less as a decade and more as a feeling — chrome, sunset, and the Yamaha DX7 as a time machine.',
    intro: 'Drive fast, feel slow. The soundtrack to a memory you never had.',
    tags: ['synthwave', 'electronic', '1980s', 'retro'],
    mood: ['energetic'],
    items: ['Nightcall', 'Resonance', 'Outland', 'Endless Summer', 'Trilogy', 'Prototype', 'Turbo Killer', 'Lost 84'],
  },
  {
    slug: 'soul-stax-motown',
    channel: 'music',
    title: 'Soul: Stax, Motown & the Groove',
    thesis:
      'Two labels, one mission: make the rhythm undeniable. We map the vocalists who turned heartbreak into something you could dance to.',
    intro: 'Horn stabs, call-and-response, and the rhythm section that built a city.',
    tags: ['soul', 'rnb', '1960s', 'vocal'],
    mood: ['party', 'energetic'],
    items: ['Whats Going On', 'Lets Stay Together', 'I Heard It Through', 'Respect', 'My Girl', 'Aint No Mountain', 'Superstition', 'Sir Duke'],
  },
  {
    slug: 'math-rock',
    channel: 'music',
    title: 'Math Rock: Counting as Feeling',
    thesis:
      'Bands who discovered that odd time signatures could carry emotion that 4/4 could not. Tapping, counter-rhythm, and the joy of the unexpected turn.',
    intro: 'Polyrhythm as a love language. Guitars that skip instead of walk.',
    tags: ['mathrock', 'instrumental', '2000s', 'indie'],
    mood: ['focused', 'energetic'],
    items: ['American Football', 'Spiderland', 'Good News', 'Animals', 'The Moon Is Down', 'Dots', 'Geography', 'Frames'],
  },
  {
    slug: 'korea-indie-city',
    channel: 'music',
    title: 'K-Indie: Seoul After Midnight',
    thesis:
      'Past the idol machine, a generation of Korean songwriters writing about rent, insomnia, and quiet rebellion in major keys.',
    intro: 'Hongdae basements, acoustic confessions, and the city that never quite sleeps.',
    tags: ['korean', 'indie', '2010s', 'acoustic'],
    mood: ['melancholy', 'relaxed'],
    items: ['Love Love Love', 'Rainbow', 'Good Person', 'Spring Above', 'Tomorrow', 'Wind Flower', 'Your Shampoo', 'Apollo 11'],
  },
  {
    slug: 'german-krautrock',
    channel: 'music',
    title: 'Krautrock: Motorik Pulse',
    thesis:
      'German electronic and rock in the 70s that abandoned verse-chorus for the trance of the repeated beat. The seed of everything ambient.',
    intro: 'Tape loops, kosmische drones, and the autobahn as rhythm section.',
    tags: ['krautrock', 'electronic', '1970s', 'german'],
    mood: ['focused', 'energetic'],
    items: ['Autobahn', 'Tago Mago', 'Neu 75', 'Phaedra', 'Monster Movie', 'Cluster 71', 'Zwei', 'Ege Bamyasi'],
  },
  {
    slug: 'french-chanson',
    channel: 'music',
    title: 'Chanson: Paris in Three Minutes',
    thesis:
      'The French art of the miniature confession. We favor the songwriters who turned a café table into a stage and a sigh into a melody.',
    intro: 'Accordion, cigarette smoke, and the precise architecture of longing.',
    tags: ['chanson', 'french', 'vocal', 'acoustic'],
    mood: ['melancholy', 'relaxed'],
    items: ['Ne Me Quitte Pas', 'La Boheme', 'Sous le Ciel', 'Quelquun', 'La Vie en Rose', 'Non Je Ne Regrette', 'Mistral Gagnant', 'Je Lattends'],
  },
  {
    slug: 'black-metal-atmosphere',
    channel: 'music',
    title: 'Atmospheric Black Metal: Frost & Memory',
    thesis:
      'When the genre stopped screaming at you and started describing a landscape. We pick the records that use blast beats as weather.',
    intro: 'Pine, reverb, and the long walk through a recording of winter.',
    tags: ['blackmetal', 'metal', '1990s', 'atmospheric'],
    mood: ['melancholy'],
    items: ['Transilvanian Hunger', 'Anthems', 'Hvis Lyset', 'Filosofem', 'Under a Funeral', 'The Mantle', 'Dead Winter', 'Varde'],
  },
  {
    slug: 'reggae-roots',
    channel: 'music',
    title: 'Roots Reggae: Dub & Doctrine',
    thesis:
      'The rhythm that colonized the world sideways. We trace roots, dub, and the studio as instrument from Kingston to the globe.',
    intro: 'Delay units, bass as sermon, and the one-drop that moves nations.',
    tags: ['reggae', 'dub', '1970s', 'roots'],
    mood: ['relaxed', 'party'],
    items: ['Catch a Fire', 'Exodus', 'Heart of the Congos', 'Super Ape', 'Two Sevens Clash', 'Dreadlocks', 'Marcus Garvey', 'War Ina Babylon'],
  },
  {
    slug: 'minimal-piano',
    channel: 'music',
    title: 'Minimal Piano: One Note at a Time',
    thesis:
      'Composers who subtracted until only the essential remained. Repetition, silence, and the listener as co-author.',
    intro: 'Prepared pianos, slow arcs, and the discipline of the held note.',
    tags: ['piano', 'classical', 'minimal', 'instrumental'],
    mood: ['focused', 'relaxed'],
    items: ['Solo Piano', 'Daughters', 'The Blue Notebooks', 'Spiegel im Spiegel', 'Verdigris', 'Objects', 'Patterns', 'Inventions'],
  },
  {
    slug: 'grunge-seattle',
    channel: 'music',
    title: 'Grunge: Flannel & Feedback',
    thesis:
      'The major label absorbed the underground and the underground forgave it. We map the bands that made alienation sound like a hook.',
    intro: 'Drop D, broken amps, and the quiet-loud-quiet that broke the 80s.',
    tags: ['grunge', 'rock', '1990s', 'seattle'],
    mood: ['melancholy', 'energetic'],
    items: ['Nevermind', 'Ten', 'Dirt', 'Core', 'Superunknown', 'In Utero', 'Dry As a Bone', 'Sweet Oblivion'],
  },
  {
    slug: 'afrobeat-pioneers',
    channel: 'music',
    title: 'Afrobeat: The Long Revolution',
    thesis:
      'Fela built a genre as protest and as party — horns interlocking for twenty minutes, rhythm as both groove and manifesto.',
    intro: 'Highlife guitar, talking drums, and the band as a small parliament.',
    tags: ['afrobeat', 'funk', '1970s', 'nigerian'],
    mood: ['party', 'energetic'],
    items: ['Zombie', 'Expensive Shit', 'Gentleman', 'Sorrow Tears', 'No Agreement', 'Teacher Dont Teach', 'Upside Down', 'Black Man'],
  },
  {
    slug: 'dream-pop',
    channel: 'music',
    title: 'Dream Pop: Reverb as Weather',
    thesis:
      'When the studio became the instrument and the voice became another texture. We collect the bands that chose haze over clarity.',
    intro: 'Shoegaze cousins, wall-of-sound, and the melody you hear through fog.',
    tags: ['dreampop', 'indie', '1980s', 'ethereal'],
    mood: ['relaxed', 'melancholy'],
    items: ['Heaven or Las Vegas', 'Souvlaki', 'Cocteau Twins', 'Loveless', 'Garlands', 'Blue Bell Knoll', 'Treasure', 'Ocean Rain'],
  },
  {
    slug: 'funk-70s',
    channel: 'music',
    title: 'Funk: The Pocket',
    thesis:
      'The rhythm section as the whole point. We pick the records where the bassline is the chorus and the beat is the argument.',
    intro: 'Syncopation, slap, and the downbeat you feel in your spine.',
    tags: ['funk', 'soul', '1970s', 'dance'],
    mood: ['party', 'energetic'],
    items: ['Mothership Connection', 'Tower of Power', 'Super Fly', 'Shining Star', 'Flash Light', 'Pick Up the Pieces', 'Cissy Strut', 'Give It Away'],
  },
  {
    slug: 'noise-rock',
    channel: 'music',
    title: 'Noise Rock: Feedback as Frontman',
    thesis:
      'Bands who decided the mistake was the message. We collect the records that weaponize the unwanted frequency.',
    intro: 'Distortion, collision, and the riff that refuses to resolve.',
    tags: ['noiserock', 'rock', '1980s', 'noise'],
    mood: ['energetic'],
    items: ['Psychocandy', 'Daydream Nation', 'Bug', 'The Jesus Lizard', 'Feedtime', 'Sonic Youth', 'Cop', 'Pussy Galore'],
  },
  {
    slug: 'trip-hop-bristol',
    channel: 'music',
    title: 'Trip-Hop: Bristol in the Rain',
    thesis:
      'Hip-hop tempos, dub space, and a melancholy that felt specifically British. The genre that made beats sound like cigarettes.',
    intro: 'Samplers, minor chords, and the city as mood board.',
    tags: ['triphop', 'electronic', '1990s', 'uk'],
    mood: ['relaxed', 'melancholy'],
    items: ['Dummy', 'Blue Lines', 'Maxinquaye', 'Protection', 'Portishead', 'Mezzanine', 'Pre-Millennium', 'Heroes'],
  },
  {
    slug: 'bluegrass-acoustic',
    channel: 'music',
    title: 'Bluegrass: Porch & Precision',
    thesis:
      'String-band music that turned virtuosity into community. We pick the players who made speed sound like home.',
    intro: 'Banjo rolls, close harmony, and the song as a front-porch argument.',
    tags: ['bluegrass', 'country', 'acoustic', 'folk'],
    mood: ['relaxed', 'party'],
    items: ['Foggy Mountain', 'Will the Circle', 'Cold Feet', 'Aereoplain', 'High Country', 'The crow', 'The Goat', 'Ring of Fire'],
  },
  {
    slug: 'house-chicago',
    channel: 'music',
    title: 'House: Chicago Built the Floor',
    thesis:
      'Four-on-the-floor as liberation. We trace the genre from garage soul to the warehouse and the drum machine as equalizer.',
    intro: 'Disco loops, piano stabs, and the kick that democratized dance.',
    tags: ['house', 'electronic', '1980s', 'chicago'],
    mood: ['party', 'energetic'],
    items: ['Your Love', 'Move Your Body', 'Acid Tracks', 'No Control', 'Can You Feel', 'Music Is the Key', 'Jack Your Body', 'The Party'],
  },
  {
    slug: 'singer-songwriter-70s',
    channel: 'music',
    title: 'The 70s Singer-Songwriter',
    thesis:
      'The decade that made the individual voice a genre. We favor the writers who turned confession into craft.',
    intro: 'Guitar, narrative, and the microphone as a trusted friend.',
    tags: ['folksinger', 'acoustic', '1970s', 'vocal'],
    mood: ['melancholy', 'relaxed'],
    items: ['Blue', 'Court and Spark', 'Tapestry', 'For the Roses', 'Landslide', 'Both Sides', 'Grace', 'Sweet Baby'],
  },
  {
    slug: 'japanese-citypop',
    channel: 'music',
    title: 'City Pop: Tokyo in Cruise Control',
    thesis:
      'Japanese pop of the 80s that imagined the future as a smooth ride — yacht rock with a Pacific view and a synthesizer smile.',
    intro: 'Tokyo highways, FM gloss, and the groove that became a meme and then a revival.',
    tags: ['citypop', 'japanese', '1980s', 'pop'],
    mood: ['relaxed', 'party'],
    items: ['Plastic Love', 'Ride on Time', 'For You', 'Mint Eyes', 'Stay With Me', 'I Love You', 'Telephone', 'Love Is a'],
  },
  {
    slug: 'hardcore-punk-80s',
    channel: 'music',
    title: '80s Hardcore: The Blur as Statement',
    thesis:
      'When punk decided faster was honest. We collect the records that compressed rebellion into under two minutes.',
    intro: 'Breakdowns, basements, and the snap of a snare as a political act.',
    tags: ['hardcore', 'punk', '1980s', 'fast'],
    mood: ['energetic'],
    items: ['Damaged', 'Zen Arcade', 'Minor Threat', 'Fear Era', 'Out of Step', 'Repulsion', 'Generic', 'Diskord'],
  },
  {
    slug: 'opera-aria',
    channel: 'music',
    title: 'Opera: The Aria as Drama',
    thesis:
      'Not the whole canon, but the moments where a single voice carries the weight of a plot. We pick arias that explain why the form survived.',
    intro: 'Orchestral swell, the held high note, and the room holding its breath.',
    tags: ['opera', 'classical', 'vocal', 'dramatic'],
    mood: ['melancholy'],
    items: ['Nessun Dorma', 'La Donna e Mobile', 'Casta Diva', 'Habanera', 'Queen of the Night', 'Vissi dArte', 'O Mio Babbino', 'Largo al Factotum'],
  },
  {
    slug: 'idm-breaks',
    channel: 'music',
    title: 'IDM: Intelligent Dance Music',
    thesis:
      'When electronic producers stopped DJing and started composing. We map the labels that made the glitch feel like melody.',
    intro: 'Broken beats, granular textures, and the laptop as orchestra.',
    tags: ['idm', 'electronic', '1990s', 'experimental'],
    mood: ['focused'],
    items: ['Selected Ambient', 'Amber', 'Music Has', 'Confield', 'LP5', 'Drukqs', 'Richard DJames', 'Come to Daddy'],
  },
  {
    slug: 'country-outlaw',
    channel: 'music',
    title: 'Outlaw Country: The Boot as Reply',
    thesis:
      'When Nashville polish met the prison yard. We pick the singers who answered the suit with the sneer.',
    intro: 'Telecaster twang, barroom truth, and the song as a middle finger.',
    tags: ['country', 'outlaw', '1970s', 'american'],
    mood: ['relaxed', 'melancholy'],
    items: ['Red Headed', 'At Folsom', 'Wanted', 'Honky Tonk', 'Mamas Dont', 'Luckenbach', 'Pancho', 'The Pilgrim'],
  },
  {
    slug: 'gospel-choir',
    channel: 'music',
    title: 'Gospel: The Choir as Engine',
    thesis:
      'The tradition that powered soul, rock, and pop underneath. We collect the recordings where the voices outrun the arrangement.',
    intro: 'Call-and-response, testifying, and the room as congregation.',
    tags: ['gospel', 'soul', 'vocal', 'church'],
    mood: ['party', 'energetic'],
    items: ['Amazing Grace', 'Oh Happy Day', 'Precious Lord', 'I Love the Lord', 'Take My Hand', 'Touch the Hem', 'How I Got', 'Total Praise'],
  },
  {
    slug: 'shoegaze-revival',
    channel: 'music',
    title: 'Shoegaze Revival: Looking Down, Feeling Up',
    thesis:
      'The 90s genre that refused to die. We map the new bands who rediscovered that volume and melody are not opposites.',
    intro: 'Pedalboards, buried vocals, and the wall that became a doorway.',
    tags: ['shoegaze', 'indie', '2010s', 'noise'],
    mood: ['relaxed', 'melancholy'],
    items: ['Bloom', 'Heaven', 'Soft Sounds', 'Depreston', 'Slowdive', 'Everything Is', 'Strange', 'No Dream'],
  },
  {
    slug: 'disco-era',
    channel: 'music',
    title: 'Disco: The Studio as Sanctuary',
    thesis:
      'Dismissed, then redeemed. We pick the records that proved four-on-the-floor could be both liberation and architecture.',
    intro: 'Strings, mirror ball, and the rhythm that outlived its obituary.',
    tags: ['disco', 'dance', '1970s', 'strings'],
    mood: ['party', 'energetic'],
    items: ['Saturday Night', 'I Feel Love', 'Le Freak', 'Dont Stop', 'Good Times', 'MacArthur Park', 'Bad Girls', 'YMCA'],
  },
  {
    slug: 'ambient-drone',
    channel: 'music',
    title: 'Drone: The Note That Refuses to End',
    thesis:
      'Minimalism pushed past the edge of event. We collect the works where stasis becomes a place you can stand in.',
    intro: 'Sustained tones, slow movement, and listening as a long exposure.',
    tags: ['drone', 'ambient', 'instrumental', 'minimal'],
    mood: ['focused', 'relaxed'],
    items: ['The Well-Tuned', 'Earth 2', 'Strumming', 'Droned', 'Two Forms', 'A Field', 'Tara', 'The Disintegration'],
  },
  {
    slug: 'punk-77',
    channel: 'music',
    title: 'Punk 77: Three Chords & A Future',
    thesis:
      'The year the underground became a headline. We map the records that proved anyone could, and most should not have.',
    intro: 'Leather, speed, and the riff as a refusal.',
    tags: ['punk', 'rock', '1977', 'uk'],
    mood: ['energetic'],
    items: ['Never Mind', 'The Clash', 'Ramones', 'Horses', 'London Calling', 'White Riot', 'Anarchy', 'Gods Save'],
  },
  {
    slug: 'flamenco-deep',
    channel: 'music',
    title: 'Flamenco: The Cry as Technique',
    thesis:
      'Not the tourist show, but the cante jondo — the deep song where technique serves grief. We pick the performers who make the guitar weep.',
    intro: 'Palmas, the held wail, and the rhythm that carries a century of exile.',
    tags: ['flamenco', 'spanish', 'acoustic', 'vocal'],
    mood: ['melancholy', 'energetic'],
    items: ['Antologia', 'El Camaron', 'Paco de Lucia', 'Sabra', 'Cafe Cantante', 'La Leyenda', 'En Vivo', 'Solo Quiero'],
  },
  {
    slug: 'psychedelic-60s',
    channel: 'music',
    title: 'Psychedelia: The Studio as Kaleidoscope',
    thesis:
      'The decade that treated recording as a drug. We collect the albums that sound like a room expanding.',
    intro: 'Tape loops, backwards guitars, and the song as a trip.',
    tags: ['psychedelic', 'rock', '1960s', 'experimental'],
    mood: ['relaxed', 'energetic'],
    items: ['Sgt Peppers', 'Piper', 'The Psychedelic', 'Pet Sounds', 'Are You Experienced', 'Surrealistic', 'The Notorious', 'Ogden'],
  },
  {
    slug: 'trap-modern',
    channel: 'music',
    title: 'Trap: The Sub as Skyline',
    thesis:
      'Southern hip-hop turned the 808 into architecture. We map the producers who built cities out of hi-hats and reverb.',
    intro: 'Triple-time rolls, the swallowed vocal, and the beat as a weather system.',
    tags: ['trap', 'hiphop', '2010s', 'southern'],
    mood: ['energetic', 'party'],
    items: ['DS2', 'Culture', 'Astroworld', 'Die Lit', 'Culture II', 'Without Warning', 'Luv Is', 'Super Slimey'],
  },
  {
    slug: 'baroque-court',
    channel: 'music',
    title: 'Baroque: The Harpsichord as Argument',
    thesis:
      'Counterpoint as the highest game. We pick the works where multiple melodies argue politely and resolve as architecture.',
    intro: 'Ornament, the figured bass, and the fugue as a perfect machine.',
    tags: ['baroque', 'classical', 'instrumental', 'harpsichord'],
    mood: ['focused'],
    items: ['Goldberg Variations', 'Brandenburg', 'The Four Seasons', 'Toccata', 'Water Music', 'Messiah', 'Canon', 'Concerto'],
  },
  {
    slug: 'emo-second-wave',
    channel: 'music',
    title: 'Emo: The Whisper as Scream',
    thesis:
      'When punk discovered therapy. We collect the records that turned diary entries into communal catharsis.',
    intro: 'Tight jeans, open tunings, and the bridge as the whole point.',
    tags: ['emo', 'rock', '2000s', 'confessional'],
    mood: ['melancholy'],
    items: ['Clarity', 'Bleed American', 'Diary', 'Something to Write', 'Deja Entendu', 'Tell All', 'Transatlantic', 'Ocean'],
  },
  {
    slug: 'salsa-newyork',
    channel: 'music',
    title: 'Salsa: The Barrio as Big Band',
    thesis:
      'New York turned Cuban forms into a city sound. We map the bands that made the montuno a neighborhood parliament.',
    intro: 'Timbales, the piano tumbao, and the dancer as co-composer.',
    tags: ['salsa', 'latin', '1970s', 'dance'],
    mood: ['party', 'energetic'],
    items: ['El Barrio', 'Fania All', 'Salsa', 'Conjunto', 'Tite Curet', 'The Message', 'Anacaona', 'Songo'],
  },
  {
    slug: 'noise-pop',
    channel: 'music',
    title: 'Noise Pop: The Hook in the Static',
    thesis:
      'When melody learned to hide inside distortion. We pick the bands that made the fuzz feel like a hug.',
    intro: 'Jangle buried in gain, the hum as warmth, and the song you half-remember.',
    tags: ['noisepop', 'indie', '1990s', 'jangle'],
    mood: ['relaxed'],
    items: ['Bee Thousand', 'Alien Lanes', 'Tiger Trap', 'Seamonsters', 'Bewitched', 'The Friends', 'Murmur', 'Fonder'],
  },
  {
    slug: 'spiritual-jazz',
    channel: 'music',
    title: 'Spiritual Jazz: The Sideways Sermon',
    thesis:
      'Jazz that prayed without a church. We collect the records where the solo becomes a meditation and the rhythm a mantra.',
    intro: 'Congas, the open fifth, and the long form as devotion.',
    tags: ['jazz', 'spiritual', '1970s', 'modal'],
    mood: ['focused', 'relaxed'],
    items: ['Thembi', 'Journey in Satch', 'Karma', 'Tauhid', 'Black Unity', 'Red Sun', 'Message from', 'World Galaxy'],
  },
  {
    slug: 'synth-pop-80s',
    channel: 'music',
    title: 'Synth-Pop: The Calculator as Crooner',
    thesis:
      'When the synthesizer learned to sing. We map the duos who made the sequencer feel like heartbreak.',
    intro: 'Drum machines, the gated reverb, and the chorus as a circuit.',
    tags: ['synthpop', 'electronic', '1980s', 'pop'],
    mood: ['relaxed', 'party'],
    items: ['Dont You Want', 'Tainted Love', 'Just Cant', 'Blue Monday', 'Sweet Dreams', 'Take On Me', 'Bizarre Love', 'Enjoy the Silence'],
  },
  {
    slug: 'americana-roots',
    channel: 'music',
    title: 'Americana: The Song as Region',
    thesis:
      'The genre that refused to let the regional dialect die. We pick the writers who map a place by its chord changes.',
    intro: 'Weathered voices, the story song, and the railroad as refrain.',
    tags: ['americana', 'folk', 'country', 'roots'],
    mood: ['relaxed', 'melancholy'],
    items: ['Sweet Old', 'Mermaid Avenue', 'Trace', 'Car Wheels', 'The Ghost', 'Plantation', 'Down the Old', 'Lucinda'],
  },
  {
    slug: 'gothic-postpunk',
    channel: 'music',
    title: 'Gothic: The minor key as identity',
    thesis:
      'Post-punk dressed in velvet. We collect the bands that turned dread into elegance and the bass into a cathedral.',
    intro: 'Reverb, the sung whisper, and the drum as a funeral march.',
    tags: ['gothic', 'postpunk', '1980s', 'dark'],
    mood: ['melancholy'],
    items: ['Pornography', 'Faith', 'Seventeen Seconds', 'Juju', 'First and Last', 'Bela Lugosi', 'The Cure', 'Mask'],
  },
  {
    slug: 'highlife-ghana',
    channel: 'music',
    title: 'Highlife: The Guitar as Celebration',
    thesis:
      'West African pop that turned the imported guitar into a local language. We map the bands that made the dance floor a hometown.',
    intro: 'Palm-wine rhythms, the bright lead, and the song as a reunion.',
    tags: ['highlife', 'african', 'guitar', 'dance'],
    mood: ['party', 'relaxed'],
    items: ['Ghana Special', 'E.T. Mensah', 'King Onyina', 'Orchestra', 'The龍 African', 'Yaa Amponsah', 'Oman', 'Koo Nimo'],
  },
  {
    slug: 'breakcore',
    channel: 'music',
    title: 'Breakcore: The Breakbeat as Collapse',
    thesis:
      'When jungle met noise and stopped apologizing. We collect the producers who treat the amen break as raw material for demolition.',
    intro: 'Chopper edits, the distorted kick, and the track as a panic attack.',
    tags: ['breakcore', 'electronic', '2000s', 'fast'],
    mood: ['energetic'],
    items: ['Rossz', 'Endless', 'Channel', 'Crack', 'Wonder', 'Break', 'Doctrine', 'Planet'],
  },
  {
    slug: 'lofi-hiphop',
    channel: 'music',
    title: 'Lo-Fi Hip-Hop: The Beat as Study Buddy',
    thesis:
      'The YouTube study stream made genre. We pick the producers who turned dusty samples into a steady companion.',
    intro: 'Vinyl crackle, the lazy snare, and the loop as a safe room.',
    tags: ['lofihiphop', 'hiphop', '2010s', 'chill'],
    mood: ['relaxed', 'focused'],
    items: ['Nujabes', 'Modal Soul', 'Reflection', 'Feather', 'Luv', 'Sakura', 'Aruarian', 'Hydeout'],
  },
  {
    slug: 'new-wave',
    channel: 'music',
    title: 'New Wave: The Quirk as Anthem',
    thesis:
      'Punk grew up, bought a synthesizer, and learned to wink. We map the bands that made irony danceable.',
    intro: 'Skinny ties, the music video, and the hook as a punchline.',
    tags: ['newwave', 'rock', '1980s', 'pop'],
    mood: ['party', 'energetic'],
    items: ['Talking Heads', 'Remain in Light', 'Rio', 'Duran Duran', 'Psycho Killer', 'Once in a Lifetime', 'Bizarre', 'Cars'],
  },
  {
    slug: 'sufi-devotional',
    channel: 'music',
    title: 'Sufi: The Song as Ascent',
    thesis:
      'Devotional music that forgot the border between performer and divine. We collect the forms where repetition becomes flight.',
    intro: 'The drone, the turning, and the verse as a staircase.',
    tags: ['sufi', 'devotional', 'middleeastern', 'vocal'],
    mood: ['focused', 'relaxed'],
    items: ['Nusrat', 'Qawwali', 'Dam Mast', 'Mustt', 'The Rain', 'Devotional', 'Raga', 'Fanna'],
  },
  {
    slug: 'vaporwave',
    channel: 'music',
    title: 'Vaporwave: The Meme as Mood',
    thesis:
      'A genre built from corporate muzak and slowed-down nostalgia. We pick the records that turn capitalism into a lullaby.',
    intro: 'Chopped mall music, the statue bust, and the aesthetic as the whole point.',
    tags: ['vaporwave', 'electronic', '2010s', 'ironic'],
    mood: ['relaxed'],
    items: ['Floral Shoppe', 'Telepath', 'I will', 'Far', '漠视', 'Laser', '新しい', 'Vektroid'],
  },
  {
    slug: 'bluegrass-women',
    channel: 'music',
    title: 'Women of Bluegrass',
    thesis:
      'The tradition that often forgot half its voices. We collect the singers and pickers who rewrote the front porch.',
    intro: 'High harmony, the fast lead, and the song as a claim.',
    tags: ['bluegrass', 'country', 'women', 'acoustic'],
    mood: ['relaxed', 'party'],
    items: ['Coaldust', 'The Female', 'Roche', 'Hazel', 'Cry', 'Wildwood', 'Pretty', 'Singing'],
  },
  {
    slug: 'post-rock',
    channel: 'music',
    title: 'Post-Rock: The Build as Form',
    thesis:
      'When rock abandoned the song for the arc. We map the bands that turn restraint into a forty-minute landslide.',
    intro: 'The quiet opening, the delayed guitar, and the climax as catharsis.',
    tags: ['postrock', 'instrumental', '1990s', 'epic'],
    mood: ['focused', 'melancholy'],
    items: ['Spiderland', 'Lift Your Skin', 'The Earth', 'F♯ A♯', 'Music for', 'Godspeed', 'Yanqui', 'Hex'],
  },
  {
    slug: 'calypso-soca',
    channel: 'music',
    title: 'Calypso & Soca: The Rhyme as Resistance',
    thesis:
      'Caribbean forms that turned satire into a national sport. We collect the performers who made the carnival a newspaper.',
    intro: 'The steel pan, the double entendre, and the road march as referendum.',
    tags: ['calypso', 'caribbean', 'dance', 'political'],
    mood: ['party', 'energetic'],
    items: ['The Mighty', 'Soca', ' Caribbean', 'Road March', 'Wine', 'Hot', 'Jump', 'Fete'],
  },
  {
    slug: 'tape-lofi',
    channel: 'music',
    title: 'Bedroom Pop: The Demo as Final',
    thesis:
      'When the bedroom became the studio and the imperfection became the style. We pick the records that wear their hiss proudly.',
    intro: 'The handheld recorder, the shy vocal, and the song as a secret.',
    tags: ['bedroompop', 'indie', '2010s', 'lofi'],
    mood: ['relaxed', 'melancholy'],
    items: ['Balloon', 'Songs', 'Loyal', 'Cendi', 'New Age', 'Still', 'February', 'Crashed'],
  },
  {
    slug: 'middle-east-oud',
    channel: 'music',
    title: 'The Oud: String as Geography',
    thesis:
      'The instrument that maps a region by its tuning. We collect the players who turn a single string into a continent.',
    intro: 'The microtone, the maqam, and the solo as a map.',
    tags: ['oud', 'middleeastern', 'instrumental', 'classical'],
    mood: ['focused', 'relaxed'],
    items: ['Marcel', 'Anouar', 'Munir', 'Naseer', 'The Cairo', 'Andalusian', 'Taqsim', 'Levant'],
  },
  {
    slug: 'garage-rock-revival',
    channel: 'music',
    title: 'Garage Revival: The Riff as Refuge',
    thesis:
      'The 2000s decided the studio was lying. We map the bands that plugged straight into the amp and the id.',
    intro: 'The fuzz, the count-in, and the song as a dare.',
    tags: ['garage', 'rock', '2000s', 'raw'],
    mood: ['energetic', 'party'],
    items: ['Is This It', 'Elephant', 'The Strokes', 'White Blood', 'Modern Age', 'Fell', 'Last Nite', 'Hard'],
  },
  {
    slug: 'experimental-vocal',
    channel: 'music',
    title: 'Extended Voice: The Throat as Instrument',
    thesis:
      'Singers who treated the voice as raw material rather than messenger. We collect the works that redefine what a sound can be.',
    intro: 'Overtones, the unpretty note, and the breath as rhythm.',
    tags: ['experimental', 'vocal', 'avant', 'instrumental'],
    mood: ['focused'],
    items: ['Meredith', 'Joan', 'Diamanda', 'Yoko', 'The Litanies', 'Vocal', 'Extreme', 'Voice'],
  },
  {
    slug: 'dreampop-shoegaze-2020s',
    channel: 'music',
    title: 'New Haze: 2020s Wall of Sound',
    thesis:
      'A new generation rediscovered that reverb is a feeling. We map the bands building cathedrals out of pedals and whisper.',
    intro: 'The washed vocal, the slow build, and the song as a fog bank.',
    tags: ['dreampop', 'shoegaze', '2020s', 'ethereal'],
    mood: ['relaxed', 'melancholy'],
    items: ['Scaring', 'A Crush', 'Get', 'Heaven', 'Glow', 'No Need', 'Hush', 'Petal'],
  },
  {
    slug: 'latin-jazz',
    channel: 'music',
    title: 'Latin Jazz: The Clave as Bridge',
    thesis:
      'When bebop met the Caribbean and both won. We collect the players who made the rhythm a conversation across oceans.',
    intro: 'The montuno, the brass, and the solo as a dance step.',
    tags: ['latinjazz', 'jazz', 'afrocuban', 'dance'],
    mood: ['party', 'energetic'],
    items: ['Manteca', 'Afro-Cuban', 'Cuban Bridge', 'The Pool', 'Cal Tjader', 'Soul Sauce', 'Mambo', 'Bird'],
  },
  {
    slug: 'metal-progressive',
    channel: 'music',
    title: 'Prog Metal: The Riff as Equation',
    thesis:
      'When metal enrolled in music school. We map the bands that turned odd meters into catharsis.',
    intro: 'The sweep, the concept album, and the breakdown as a plot twist.',
    tags: ['progmetal', 'metal', '2000s', 'technical'],
    mood: ['energetic', 'focused'],
    items: ['Metropolis', 'Images', 'Lateralus', 'Blackwater', 'The Dance', 'Octavarium', 'Panic', 'Train'],
  },
];
