// 一次性回填：把 seeds 的 theme.mood 注入到已生成的 generated-*.ts（不重跑 API）
// 通过 item.seedName → theme.items 反查所属 theme 的 mood
import { writeFileSync as wf, readFileSync as rf } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

const targets = [
  { file: 'lib/media/generated-music.ts', varName: 'MUSIC_ITEMS', seedMod: '../lib/media/seeds-music.ts', seedExp: 'MUSIC_THEMES' },
  { file: 'lib/media/generated-games.ts', varName: 'GAME_ITEMS', seedMod: '../lib/media/seeds-games.ts', seedExp: 'GAME_THEMES' },
  { file: 'lib/media/generated-film.ts', varName: 'FILM_ITEMS', seedMod: '../lib/media/seeds-film.ts', seedExp: 'FILM_THEMES' },
  { file: 'lib/media/generated-tv.ts', varName: 'TV_ITEMS', seedMod: '../lib/media/seeds-tv.ts', seedExp: 'TV_THEMES' },
];

const seedImports = await Promise.all(targets.map((t) => import(t.seedMod)));
const moodBySeed = {};
targets.forEach((t, i) => {
  const themes = seedImports[i][t.seedExp] || [];
  for (const th of themes) {
    for (const name of th.items) {
      if (th.mood && th.mood.length) moodBySeed[name] = th.mood;
    }
  }
});
console.log('mood map entries:', Object.keys(moodBySeed).length);

for (const t of targets) {
  const path = join(ROOT, t.file);
  const src = rf(path, 'utf8');
  // 提取 JSON 数组（export const X: CurationItem[] = [...]）
  const m = src.match(/export const \w+: CurationItem\[\] = (\[[\s\S]*\]);/);
  if (!m) { console.log(`skip ${t.file} (no match)`); continue; }
  const items = JSON.parse(m[1]);
  let patched = 0;
  for (const it of items) {
    const mood = moodBySeed[it.seedName];
    if (mood && (!it.moods || it.moods.length === 0)) {
      it.moods = mood;
      patched++;
    }
  }
  const ts = `// AUTO-GENERATED by scripts/${t.file.split('/').pop().replace('generated', 'fetch').replace('.ts', '.mjs')} — do not edit\nimport type { CurationItem } from './musicbrainz';\nexport const ${t.varName}: CurationItem[] = ${JSON.stringify(items, null, 2)};\n`;
  wf(path, ts);
  console.log(`${t.file}: ${patched} items patched with moods (total ${items.length})`);
}
console.log('Backfill done.');
