// 构建期数据管道：TVmaze 名称→id 解析 + 元数据（TV 专用，绕开 TMDB 限流）
// TVmaze 无需 API key，20 req/10s 无限流层 → TV 376 条几分钟跑完
// 生成 public/data/tv-items.json + lib/media/generated-tv.ts
// 用法：node scripts/fetch-tvmaze.mjs [write]
import { writeFileSync as wf, mkdirSync as mk, existsSync as ex, readFileSync as rf } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const CACHE_DIR = join(ROOT, 'cache');
const DATA_DIR = join(ROOT, 'public', 'data');
const TVMAZE = 'https://api.tvmaze.com';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

mk(CACHE_DIR, { recursive: true });
mk(DATA_DIR, { recursive: true });

const RESOLVE_CACHE = join(CACHE_DIR, 'tvmaze-resolve.json');
let resolved = ex(RESOLVE_CACHE) ? JSON.parse(rf(RESOLVE_CACHE, 'utf8')) : {};
const saveResolve = () => wf(RESOLVE_CACHE, JSON.stringify(resolved, null, 2));

// 去 HTML 标签 + 压缩空白（TVmaze summary 是带 <p><b> 的 HTML 片段）
function cleanSummary(html) {
  return (html || '')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&#39;|&quot;|&amp;|&nbsp;/g, (m) => ({ '&#39;': "'", '&quot;': '"', '&amp;': '&', '&nbsp;': ' ' }[m]))
    .replace(/\s+/g, ' ')
    .trim();
}
function toSynopsis(summary) {
  if (!summary || summary.length < 40) return null;
  const sentences = summary.split(/(?<=[.!?])\s+/).map((s) => s.trim()).filter(Boolean);
  let pick = sentences[0] || '';
  if (sentences[1] && pick.length < 130) pick += ' ' + sentences[1];
  pick = pick.replace(/\s+/g, ' ').trim();
  if (pick.length > 230) pick = pick.slice(0, 227).replace(/\s+\S*$/, '') + '…';
  return pick || null;
}

async function tvmazeGet(path, attempt = 1) {
  await sleep(350); // 20 req/10s 安全节奏
  let res;
  try {
    res = await fetch(`${TVMAZE}${path}`, { headers: { Accept: 'application/json' } });
  } catch (e) {
    if (attempt >= 4) throw e;
    await sleep(1500);
    return tvmazeGet(path, attempt + 1);
  }
  if (res.status === 429) {
    // 理论上 TVmaze 免费层不触发，但防御性处理
    if (attempt >= 6) throw new Error('TVmaze 429 persistent');
    const wait = 5000 + attempt * 3000;
    console.log(`  TVmaze 429, wait ${Math.round(wait / 1000)}s...`);
    await sleep(wait);
    return tvmazeGet(path, attempt + 1);
  }
  if (!res.ok) {
    if (attempt >= 3) return null;
    await sleep(1000);
    return tvmazeGet(path, attempt + 1);
  }
  return res.json();
}

async function resolveShow(name, slug, moods = []) {
  const cacheKey = `tv:${name}`;
  if (resolved[cacheKey] !== undefined) return resolved[cacheKey];
  const q = encodeURIComponent(name);
  const search = await tvmazeGet(`/singlesearch/shows?q=${q}&embed=cast`);
  if (!search) {
    // 退而用模糊搜索取首结果
    const list = await tvmazeGet(`/search/shows?q=${q}`);
    if (!list || !list.length) { resolved[cacheKey] = null; saveResolve(); return null; }
    var show = list[0].show;
  } else {
    var show = search;
  }
  const year = (show.premiered || '').slice(0, 4);
  const network = show.network?.name || show.webChannel?.name || '';
  const genres = (show.genres || []).map((g) => g.toLowerCase());
  const rating = show.rating?.average ? String(show.rating.average) : '';
  const synopsis = toSynopsis(cleanSummary(show.summary));
  const item = {
    source: 'tv',
    refId: String(show.id),
    title: show.name,
    seedName: name,
    creator: network,
    year: year || '',
    tags: ['tv', ...genres].slice(0, 8),
    moods: moods || [],
    cover: null, // TVmaze 无稳定直链海报，用占位
    url: `/tv/${slug}/`,
    synopsis: synopsis || undefined,
    refId: show.externals?.imdb ? String(show.externals.imdb) : String(show.id),
  };
  resolved[cacheKey] = item;
  saveResolve();
  return item;
}

async function main() {
  const { TV_THEMES } = await import('../lib/media/seeds-tv.ts');
  const tasks = [];
  for (const theme of TV_THEMES) {
    for (const name of theme.items) {
      tasks.push({ name, slug: theme.slug, moods: theme.mood || [] });
    }
  }
  console.log(`TVmaze names to resolve: ${tasks.length} (cached: ${Object.keys(resolved).length})`);

  const itemsMap = {};
  for (const { name, slug, moods } of tasks) {
    const key = `tv:${name}`;
    const c = resolved[key];
    if (c && c !== null && c.refId) {
      if (!c.moods || c.moods.length === 0) c.moods = moods;
      itemsMap[key] = c;
    } else if (c && !c.refId) delete resolved[key];
  }
  const persist = () => {
    const tvItems = Object.values(itemsMap);
    wf(join(DATA_DIR, 'tv-items.json'), JSON.stringify(tvItems, null, 2));
    const ts = `// AUTO-GENERATED by scripts/fetch-tvmaze.mjs — do not edit\nimport type { CurationItem } from './musicbrainz';\nexport const TV_ITEMS: CurationItem[] = ${JSON.stringify(tvItems, null, 2)};\n`;
    wf(join(ROOT, 'lib', 'media', 'generated-tv.ts'), ts);
  };
  persist();

  for (const { name, slug, moods } of tasks) {
    const key = `tv:${name}`;
    if (resolved[key] !== undefined) continue;
    try {
      const item = await resolveShow(name, slug, moods);
      if (!item) { console.log(`  ✗ unresolved: ${name}`); continue; }
      itemsMap[key] = item;
      persist();
      console.log(`  ✓ ${name} → ${item.title} (${item.year || '?'}) ${item.cover ? 'cover' : 'no-cover'}`);
    } catch (e) {
      console.log(`  ✗ error ${name}: ${e.message}`);
    }
  }
  const tvItems = Object.values(itemsMap);
  persist();
  console.log(`\nDone. ${tvItems.length} tv items → generated-tv.ts`);
}

main().catch((e) => { console.error(e); process.exit(1); });
