// scripts/fetch-omdb.mjs
// 用 OMDb API (apikey from env OMDb_API_KEY) 补全 film 频道元数据，彻底绕开 TMDB 限流。
// 按标题搜索（t=），输出 CurationItem 统一字段，断点续传 + 增量落盘。
// 生成 lib/media/generated-film.ts + public/data/film-items.json
import { writeFileSync as wf, existsSync, readFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const DATA_DIR = join(ROOT, 'public', 'data');
mkdirSync(DATA_DIR, { recursive: true });
const CACHE = join(ROOT, 'cache', 'omdb-resolve.json');
const KEY = process.env.OMDB_API_KEY;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const slug = (s) => (s || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

if (!KEY) { console.error('OMDB_API_KEY not set.'); process.exit(1); }
const resolved = existsSync(CACHE) ? JSON.parse(readFileSync(CACHE, 'utf8')) : {};

function toSynopsis(s) {
  if (!s || s === 'N/A') return '';
  return s.replace(/"/g, "'").replace(/\s+/g, ' ').trim().slice(0, 600);
}

async function fetchByTitle(name) {
  await sleep(220); // 保守速率，避免触发 OMDb 防护（免费层 1000 req/day）
  const url = `http://www.omdbapi.com/?t=${encodeURIComponent(name)}&apikey=${KEY}`;
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), 15000);
  try {
    const r = await fetch(url, { signal: ctrl.signal });
    const j = await r.json();
    clearTimeout(timer);
    if (j.Response !== 'True') return null;
    return j;
  } catch {
    clearTimeout(timer);
    return null;
  }
}

async function resolveFilm(name, moods) {
  const j = await fetchByTitle(name);
  if (!j) return null;
  const cover = j.Poster && j.Poster !== 'N/A' ? j.Poster : null;
  const creator = [j.Director, (j.Actors || '').split(',')[0]].filter((x) => x && x !== 'N/A').join(', ');
  const tags = (j.Genre || '').split(',').map((g) => slug(g.trim())).filter(Boolean);
  return {
    source: 'film', refId: j.imdbID || '', title: j.Title || name, seedName: name,
    creator, year: (j.Year || '').slice(0, 4),
    tags: tags.length ? tags : ['film'],
    cover, url: '', synopsis: toSynopsis(j.Plot) || undefined,
    moods: moods || [],
  };
}

const { FILM_THEMES } = await import('../lib/media/seeds-film.ts');

// 构建 themeOf 映射（name -> mood）
const themeOf = {};
for (const t of FILM_THEMES) for (const n of t.items) themeOf[n] = t;

const tasks = [];
for (const theme of FILM_THEMES) {
  for (const name of theme.items) {
    tasks.push({ name, slug: theme.slug, moods: theme.mood || [] });
  }
}
console.log(`OMDb film names to resolve: ${tasks.length} (cached: ${Object.keys(resolved).length})`);

// 预填充
const itemsMap = {};
for (const { name } of tasks) {
  if (resolved[name] && resolved[name] !== null) itemsMap[name] = resolved[name];
}

const persist = () => {
  const all = Object.values(itemsMap);
  wf(join(DATA_DIR, 'film-items.json'), JSON.stringify(all, null, 2));
  const ts = `// AUTO-GENERATED by scripts/fetch-omdb.mjs — do not edit
import type { CurationItem } from './musicbrainz';
export const FILM_ITEMS: CurationItem[] = ${JSON.stringify(all, null, 2)};
`;
  wf(join(ROOT, 'lib', 'media', 'generated-film.ts'), ts);
  wf(CACHE, JSON.stringify(resolved, null, 2));
};

for (const { name, slug, moods } of tasks) {
  if (resolved[name] !== undefined) continue;
  try {
    const item = await resolveFilm(name, moods);
    if (!item) { console.log(`  ✗ unresolved: ${name}`); resolved[name] = null; continue; }
    itemsMap[name] = item;
    resolved[name] = item;
    persist();
    console.log(`  ✓ ${name} → ${item.title} (${item.year || '?'}) ${item.cover ? 'cover' : 'no-cover'}`);
  } catch (e) {
    console.log(`  ✗ error ${name}: ${e.message}`);
  }
}

persist();
const all = Object.values(itemsMap);
console.log(`\nDone. ${all.length} film items → generated-film.ts`);
